<script>var dwn_ns=dwn_ns||{};  {# features #}  {%- if geo_location_enabled is defined %} dwn_ns["geo_location_enabled"] = {{geo_location_enabled}}; {% endif %}  {%- if device_sensor_enabled is defined %} dwn_ns["device_sensor_enabled"] = {{device_sensor_enabled}}; {% endif %}  {# fp coming back triggers #} {%- if dwn_fp_ajax is defined %} dwn_ns["dwn_fp_ajax"] = {{dwn_fp_ajax}}; {% endif %} {%- if dwn_fp_fetch is defined %} dwn_ns["dwn_fp_fetch"] = {{dwn_fp_fetch}}; {% endif %}  {# remove the newline, make it hard to read #} /* raw_fingerprinting.js */
function aa(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}}function t(b){var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return c?c.call(b):{next:aa(b)}}function ba(b){if(!(b instanceof Array)){b=t(b);for(var c,d=[];!(c=b.next()).done;)d.push(c.value);b=d}return b}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){if(b==Array.prototype||b==Object.prototype)return b;b[c]=d.value;return b};
function da(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var fa=da(this);function ha(b,c){if(c)a:{var d=fa;b=b.split(".");for(var e=0;e<b.length-1;e++){var g=b[e];if(!(g in d))break a;d=d[g]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&ca(d,b,{configurable:!0,writable:!0,value:c})}}var ia;
if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={D:!0},la={};try{la.__proto__=ka;ja=la.D;break a}catch(b){}ja=!1}ia=ja?function(b,c){b.__proto__=c;if(b.__proto__!==c)throw new TypeError(b+" is not extensible");return b}:null}var ma=ia;function na(){this.l=!1;this.g=null;this.c=void 0;this.a=1;this.i=this.f=0;this.u=this.b=null}function pa(b){if(b.l)throw new TypeError("Generator is already running");b.l=!0}na.prototype.m=function(b){this.c=b};
function qa(b,c){b.b={v:c,B:!0};b.a=b.f||b.i}na.prototype.return=function(b){this.b={return:b};this.a=this.i};function u(b,c,d){b.a=d;return{value:c}}na.prototype.j=function(b){this.a=b};function ra(b){b.f=0;b.i=5}function sa(b){b.f=0;var c=b.b.v;b.b=null;return c}function ta(b){b.u=[b.b];b.f=0;b.i=0}function ua(b){var c=b.u.splice(0)[0];(c=b.b=b.b||c)?c.B?b.a=b.f||b.i:void 0!=c.j&&b.i<c.j?(b.a=c.j,b.b=null):b.a=b.i:b.a=0}function va(b){this.a=new na;this.b=b}
function wa(b,c){pa(b.a);var d=b.a.g;if(d)return ya(b,"return"in d?d["return"]:function(e){return{value:e,done:!0}},c,b.a.return);b.a.return(c);return za(b)}function ya(b,c,d,e){try{var g=c.call(b.a.g,d);if(!(g instanceof Object))throw new TypeError("Iterator result "+g+" is not an object");if(!g.done)return b.a.l=!1,g;var h=g.value}catch(m){return b.a.g=null,qa(b.a,m),za(b)}b.a.g=null;e.call(b.a,h);return za(b)}
function za(b){for(;b.a.a;)try{var c=b.b(b.a);if(c)return b.a.l=!1,{value:c.value,done:!1}}catch(d){b.a.c=void 0,qa(b.a,d)}b.a.l=!1;if(b.a.b){c=b.a.b;b.a.b=null;if(c.B)throw c.v;return{value:c.return,done:!0}}return{value:void 0,done:!0}}
function Aa(b){this.next=function(c){pa(b.a);b.a.g?c=ya(b,b.a.g.next,c,b.a.m):(b.a.m(c),c=za(b));return c};this.throw=function(c){pa(b.a);b.a.g?c=ya(b,b.a.g["throw"],c,b.a.m):(qa(b.a,c),c=za(b));return c};this.return=function(c){return wa(b,c)};this[Symbol.iterator]=function(){return this}}function B(b,c){c=new Aa(new va(c));ma&&b.prototype&&ma(c,b.prototype);return c}
ha("Symbol",function(b){function c(g){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new d("jscomp_symbol_"+(g||"")+"_"+e++,g)}function d(g,h){this.a=g;ca(this,"description",{configurable:!0,writable:!0,value:h})}if(b)return b;d.prototype.toString=function(){return this.a};var e=0;return c});
ha("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<c.length;d++){var e=fa[c[d]];"function"===typeof e&&"function"!=typeof e.prototype[b]&&ca(e.prototype,b,{configurable:!0,writable:!0,value:function(){return Ba(aa(this))}})}return b});function Ba(b){b={next:b};b[Symbol.iterator]=function(){return this};return b}
ha("Promise",function(b){function c(m){this.b=0;this.g=void 0;this.a=[];var q=this.c();try{m(q.resolve,q.reject)}catch(n){q.reject(n)}}function d(){this.a=null}function e(m){return m instanceof c?m:new c(function(q){q(m)})}if(b)return b;d.prototype.b=function(m){if(null==this.a){this.a=[];var q=this;this.c(function(){q.g()})}this.a.push(m)};var g=fa.setTimeout;d.prototype.c=function(m){g(m,0)};d.prototype.g=function(){for(;this.a&&this.a.length;){var m=this.a;this.a=[];for(var q=0;q<m.length;++q){var n=
m[q];m[q]=null;try{n()}catch(r){this.f(r)}}}this.a=null};d.prototype.f=function(m){this.c(function(){throw m;})};c.prototype.c=function(){function m(r){return function(w){n||(n=!0,r.call(q,w))}}var q=this,n=!1;return{resolve:m(this.J),reject:m(this.f)}};c.prototype.J=function(m){if(m===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(m instanceof c)this.K(m);else{a:switch(typeof m){case "object":var q=null!=m;break a;case "function":q=!0;break a;default:q=!1}q?this.u(m):this.i(m)}};
c.prototype.u=function(m){var q=void 0;try{q=m.then}catch(n){this.f(n);return}"function"==typeof q?this.R(q,m):this.i(m)};c.prototype.f=function(m){this.l(2,m)};c.prototype.i=function(m){this.l(1,m)};c.prototype.l=function(m,q){if(0!=this.b)throw Error("Cannot settle("+m+", "+q+"): Promise already settled in state"+this.b);this.b=m;this.g=q;this.m()};c.prototype.m=function(){if(null!=this.a){for(var m=0;m<this.a.length;++m)h.b(this.a[m]);this.a=null}};var h=new d;c.prototype.K=function(m){var q=this.c();
m.s(q.resolve,q.reject)};c.prototype.R=function(m,q){var n=this.c();try{m.call(q,n.resolve,n.reject)}catch(r){n.reject(r)}};c.prototype.then=function(m,q){function n(z,E){return"function"==typeof z?function(L){try{r(z(L))}catch(C){w(C)}}:E}var r,w,x=new c(function(z,E){r=z;w=E});this.s(n(m,r),n(q,w));return x};c.prototype.catch=function(m){return this.then(void 0,m)};c.prototype.s=function(m,q){function n(){switch(r.b){case 1:m(r.g);break;case 2:q(r.g);break;default:throw Error("Unexpected state: "+
r.b);}}var r=this;null==this.a?h.b(n):this.a.push(n)};c.resolve=e;c.reject=function(m){return new c(function(q,n){n(m)})};c.race=function(m){return new c(function(q,n){for(var r=t(m),w=r.next();!w.done;w=r.next())e(w.value).s(q,n)})};c.all=function(m){var q=t(m),n=q.next();return n.done?e([]):new c(function(r,w){function x(L){return function(C){z[L]=C;E--;0==E&&r(z)}}var z=[],E=0;do z.push(void 0),E++,e(n.value).s(x(z.length-1),w),n=q.next();while(!n.done)})};return c});
ha("Object.entries",function(b){return b?b:function(c){var d=[],e;for(e in c)Object.prototype.hasOwnProperty.call(c,e)&&d.push([e,c[e]]);return d}});
function Ca(b){var c=typeof b;if("object"==c)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return c;var d=Object.prototype.toString.call(b);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof b.call)return"object";return c}function Da(b,c){function d(){}d.prototype=c.prototype;b.prototype=new d;b.prototype.constructor=b};dwn_ns=dwn_ns||{};dwn_ns.dwn_log||(dwn_ns.dwn_log=function(b){"string"!==typeof b&&(b="common");var c="enable_log";c=c+"_"+b;return function(){var d=arguments,e=!1;try{e={{ profiling.javascript.debug_enable }},"boolean"===typeof e&&e||"boolean"===typeof dwn_ns[c]&&(e=dwn_ns[c])}catch(m){}if(e){e="";for(var g=0;g<d.length;g++){var h=d[g];"object"===typeof h?h=h?JSON.stringify(h,null,4):"null":"undefined"===typeof h&&(h="undefined");0===g?e=h:e+=", "+h}d=(new Date).toISOString()+"["+b+"]: "+e;console.log(d)}}});
dwn_ns.add_event||(dwn_ns.add_event=function(b,c,d){try{if("addEventListener"in window)b.addEventListener(c,d,!1);else{var e="on"+c;if("attachEvent"in window)b.attachEvent(e,d);else{var g=b[e];b[e]="undefined"===typeof g?d:function(){g();d(event)}}}}catch(h){console.error("Failed to add DwnEvent:",b,c,h)}});
dwn_ns.remove_event||(dwn_ns.remove_event=function(b,c,d){try{"removeEventListener"in window?b.removeEventListener(c,d,!1):"dettachEvent"in window?b.detachEvent("on"+c,d):console.error("Can't remove event:",b,c)}catch(e){console.error("Failed to add DwnEvent:",b,c,e)}});
dwn_ns.calc_stats||(dwn_ns.calc_stats=function(b,c,d){if("undefined"!==typeof c&&0!==c.length){var e=function(x){return Math.round(100*x)/100},g=c.length,h=Math.floor(g/2);c.sort(function(x,z){return x-z});var m=c.reduce(function(x,z){return x+z},0),q=c[0],n=c[g-1],r=Math.floor(m/g);g=Math.sqrt(c.map(function(x){return Math.pow(x-r,2)}).reduce(function(x,z){return x+z},0)/g);var w=0!==h%2?c[h]:Math.floor((c[h-1]+c[h])/2);c=c.map(function(x){return Math.abs(x-w)}).sort(function(x,z){return x-z});h=
0!==h%2?c[h]:Math.floor((c[h-1]+c[h])/2);b[d+"_avg"]=e(r);b[d+"_std_dev"]=e(g);b[d+"_min"]=e(q);b[d+"_max"]=e(n);b[d+"_mad"]=e(h);b[d+"_median"]=e(w)}});dwn_ns.add_value||(dwn_ns.add_value=function(b,c,d,e){"undefined"!==typeof d&&(b[c]="boolean"===typeof e&&e||"undefined"===typeof b[c]?d:b[c]+d)});dwn_ns.add_count||(dwn_ns.add_count=function(b,c){"undefined"===typeof b[c]?b[c]=1:b[c]++});dwn_ns.time_diff||(dwn_ns.time_diff=function(b){return Date.now()-b});var Ea=Array.prototype.map?function(b,c){return Array.prototype.map.call(b,c,void 0)}:function(b,c){for(var d=b.length,e=Array(d),g="string"===typeof b?b.split(""):b,h=0;h<d;h++)h in g&&(e[h]=c.call(void 0,g[h],h,b));return e};var Ha=null;function Ia(b){var c=b.length,d=3*c/4;d%3?d=Math.floor(d):-1!="=.".indexOf(b[c-1])&&(d=-1!="=.".indexOf(b[c-2])?d-2:d-1);var e=new Uint8Array(d),g=0;Ja(b,function(h){e[g++]=h});return e.subarray(0,g)}
function Ja(b,c){function d(n){for(;e<b.length;){var r=b.charAt(e++),w=Ha[r];if(null!=w)return w;if(!/^[\s\xa0]*$/.test(r))throw Error("Unknown base64 encoding at char: "+r);}return n}Ka();for(var e=0;;){var g=d(-1),h=d(0),m=d(64),q=d(64);if(64===q&&-1===g)break;c(g<<2|h>>4);64!=m&&(c(h<<4&240|m>>2),64!=q&&c(m<<6&192|q))}}
function Ka(){if(!Ha){Ha={};for(var b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),c=["+/=","+/","-_=","-_.","-_"],d=0;5>d;d++)for(var e=b.concat(c[d].split("")),g=0;g<e.length;g++){var h=e[g];void 0===Ha[h]&&(Ha[h]=g)}}};var F=0,G=0;function La(){this.a=[]}La.prototype.length=function(){return this.a.length};function Ma(b){var c=b.a;b.a=[];return c}function H(b,c){for(;127<c;)b.a.push(c&127|128),c>>>=7;b.a.push(c)}function Na(b,c){if(0<=c)H(b,c);else{for(var d=0;9>d;d++)b.a.push(c&127|128),c>>=7;b.a.push(1)}};function Oa(){this.c=[];this.b=0;this.a=new La}function Pa(b,c){H(b.a,8*c+2);c=Ma(b.a);b.c.push(c);b.b+=c.length;c.push(b.b);return c}function Qa(b,c){var d=c.pop();for(d=b.b+b.a.length()-d;127<d;)c.push(d&127|128),d>>>=7,b.b++;c.push(d);b.b++}
function Ra(b,c,d){if(null!=d){H(b.a,8*c);b=b.a;var e=d;d=0>e;e=Math.abs(e);c=e>>>0;e=Math.floor((e-c)/4294967296);e>>>=0;d&&(e=~e>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,e++,4294967295<e&&(e=0)));F=c;G=e;d=F;for(c=G;0<c||127<d;)b.a.push(d&127|128),d=(d>>>7|c<<25)>>>0,c>>>=7;b.a.push(d)}}function J(b,c,d){null!=d&&null!=d&&(H(b.a,8*c),Na(b.a,d))}
function K(b,c,d){if(null!=d){H(b.a,8*c+5);b=b.a;var e=d;e=(d=0>e?1:0)?-e:e;0===e?0<1/e?F=G=0:(G=0,F=2147483648):isNaN(e)?(G=0,F=2147483647):3.4028234663852886E38<e?(G=0,F=(d<<31|2139095040)>>>0):1.1754943508222875E-38>e?(e=Math.round(e/Math.pow(2,-149)),G=0,F=(d<<31|e)>>>0):(c=Math.floor(Math.log(e)/Math.LN2),e*=Math.pow(2,-c),e=Math.round(8388608*e)&8388607,G=0,F=(d<<31|c+127<<23|e)>>>0);d=F;b.a.push(d>>>0&255);b.a.push(d>>>8&255);b.a.push(d>>>16&255);b.a.push(d>>>24&255)}}
function M(b,c,d){null!=d&&(H(b.a,8*c),b.a.a.push(d?1:0))}function Sa(b,c,d){null!=d&&(H(b.a,8*c),Na(b.a,d))}
function N(b,c,d){if(null!=d){c=Pa(b,c);for(var e=b.a,g=0;g<d.length;g++){var h=d.charCodeAt(g);if(128>h)e.a.push(h);else if(2048>h)e.a.push(h>>6|192),e.a.push(h&63|128);else if(65536>h)if(55296<=h&&56319>=h&&g+1<d.length){var m=d.charCodeAt(g+1);56320<=m&&57343>=m&&(h=1024*(h-55296)+m-56320+65536,e.a.push(h>>18|240),e.a.push(h>>12&63|128),e.a.push(h>>6&63|128),e.a.push(h&63|128),g++)}else e.a.push(h>>12|224),e.a.push(h>>6&63|128),e.a.push(h&63|128)}Qa(b,c)}}
function Ta(b,c,d){null!=d&&(d=d.constructor===Uint8Array?d:d.constructor===ArrayBuffer?new Uint8Array(d):"undefined"!=typeof Buffer&&d.constructor===Buffer?new Uint8Array(d):d.constructor===Array?new Uint8Array(d):d.constructor===String?Ia(d):new Uint8Array(0),H(b.a,8*c+2),H(b.a,d.length),c=Ma(b.a),b.c.push(c),b.c.push(d),b.b+=c.length+d.length)}function Ua(b,c,d,e){null!=d&&(c=Pa(b,c),e(d,b),Qa(b,c))}function Va(b,c,d){if(null!=d)for(var e=0;e<d.length;e++)N(b,c,d[e])}
function Wa(b,c,d,e){if(null!=d)for(var g=0;g<d.length;g++){var h=Pa(b,c);e(d[g],b);Qa(b,h)}};function Xa(){}var Ya="function"==typeof Uint8Array;function Za(b,c,d){b.a=null;c||(c=[]);b.i=void 0;b.c=-1;b.h=c;a:{if(c=b.h.length){--c;var e=b.h[c];if(!(null===e||"object"!=typeof e||"array"==Ca(e)||Ya&&e instanceof Uint8Array)){b.f=c-b.c;b.b=e;break a}}b.f=Number.MAX_VALUE}b.g={};if(d)for(c=0;c<d.length;c++)e=d[c],e<b.f?(e+=b.c,b.h[e]=b.h[e]||$a):(ab(b),b.b[e]=b.b[e]||$a)}var $a=[];function ab(b){var c=b.f+b.c;b.h[c]||(b.b=b.h[c]={})}
function O(b,c){if(c<b.f){c+=b.c;var d=b.h[c];return d===$a?b.h[c]=[]:d}if(b.b)return d=b.b[c],d===$a?b.b[c]=[]:d}function P(b,c,d){c<b.f?b.h[c+b.c]=d:(ab(b),b.b[c]=d)}function bb(b,c,d){b.a||(b.a={});if(!b.a[d]){var e=O(b,d);e&&(b.a[d]=new c(e))}return b.a[d]}function cb(b,c,d){b.a||(b.a={});if(!b.a[d]){for(var e=O(b,d),g=[],h=0;h<e.length;h++)g[h]=new c(e[h]);b.a[d]=g}c=b.a[d];c==$a&&(c=b.a[d]=[]);return c}function db(b,c,d){b.a||(b.a={});var e=d?d.h:d;b.a[c]=d;P(b,c,e)}
function eb(b,c,d){b.a||(b.a={});d=d||[];for(var e=[],g=0;g<d.length;g++)e[g]=d[g].h;b.a[c]=d;P(b,c,e)}Xa.prototype.toString=function(){return this.h.toString()};Xa.prototype.getExtension=function(b){if(this.b){this.a||(this.a={});var c=b.c;if(b.f){if(b.b())return this.a[c]||(this.a[c]=Ea(this.b[c]||[],function(d){return new b.a(d)})),this.a[c]}else if(b.b())return!this.a[c]&&this.b[c]&&(this.a[c]=new b.a(this.b[c])),this.a[c];return this.b[c]}};function fb(b){Za(this,b,null)}Da(fb,Xa);function gb(b){Za(this,b,hb)}Da(gb,Xa);function jb(b){Za(this,b,kb)}Da(jb,Xa);function lb(b){Za(this,b,mb)}Da(lb,Xa);function nb(b){Za(this,b,ob)}Da(nb,Xa);function pb(b){Za(this,b,qb)}Da(pb,Xa);function rb(b,c){var d=O(b,1);null!=d&&J(c,1,d);d=O(b,2);null!=d&&K(c,2,d);d=O(b,3);null!=d&&K(c,3,d);d=O(b,4);null!=d&&K(c,4,d);d=O(b,5);null!=d&&K(c,5,d);d=O(b,6);null!=d&&K(c,6,d);d=O(b,7);null!=d&&K(c,7,d)}var hb=[12,31];
function sb(b,c){var d=O(b,1);null!=d&&N(c,1,d);d=O(b,2);null!=d&&N(c,2,d);d=O(b,3);null!=d&&N(c,3,d);d=O(b,4);null!=d&&N(c,4,d);d=O(b,5);null!=d&&N(c,5,d);d=O(b,6);null!=d&&J(c,6,d);d=O(b,7);null!=d&&J(c,7,d);d=O(b,8);null!=d&&J(c,8,d);d=O(b,9);null!=d&&J(c,9,d);d=O(b,10);null!=d&&null!=d&&Ra(c,10,d);d=O(b,11);null!=d&&J(c,11,d);d=O(b,12);0<d.length&&Va(c,12,d);d=O(b,13);null!=d&&J(c,13,d);d=O(b,14);null!=d&&J(c,14,d);d=O(b,15);null!=d&&J(c,15,d);d=O(b,16);null!=d&&J(c,16,d);d=O(b,17);null!=d&&J(c,
17,d);d=O(b,18);null!=d&&J(c,18,d);d=O(b,19);null!=d&&J(c,19,d);d=O(b,20);null!=d&&J(c,20,d);d=O(b,21);null!=d&&J(c,21,d);d=O(b,22);null!=d&&J(c,22,d);d=O(b,23);null!=d&&J(c,23,d);d=O(b,24);null!=d&&J(c,24,d);d=O(b,25);null!=d&&J(c,25,d);d=O(b,26);null!=d&&J(c,26,d);d=O(b,27);null!=d&&J(c,27,d);d=O(b,28);null!=d&&J(c,28,d);d=O(b,29);null!=d&&J(c,29,d);d=O(b,30);null!=d&&J(c,30,d);d=cb(b,fb,31);0<d.length&&Wa(c,31,d,rb);d=O(b,32);null!=d&&J(c,32,d)}var kb=[8];
function tb(b,c){var d=O(b,1);null!=d&&J(c,1,d);d=O(b,2);null!=d&&null!=d&&Ra(c,2,d);d=O(b,3);null!=d&&J(c,3,d);d=O(b,4);null!=d&&J(c,4,d);d=O(b,5);null!=d&&J(c,5,d);d=O(b,6);null!=d&&J(c,6,d);d=O(b,7);null!=d&&J(c,7,d);d=cb(b,fb,8);0<d.length&&Wa(c,8,d,rb)}var mb=[5];function ub(b,c){var d=O(b,1);null!=d&&J(c,1,d);d=O(b,2);null!=d&&J(c,2,d);d=O(b,3);null!=d&&J(c,3,d);d=O(b,4);null!=d&&M(c,4,d);d=cb(b,fb,5);0<d.length&&Wa(c,5,d,rb)}var ob=[3];
function vb(b,c){var d=O(b,1);null!=d&&Sa(c,1,d);d=O(b,2);null!=d&&Sa(c,2,d);d=cb(b,fb,3);0<d.length&&Wa(c,3,d,rb)}var qb=[12,13,55,66];function wb(b){var c=navigator.platform;"MacIntel"===c&&xb()&&!yb()&&("iPad"===navigator.platform?c=!0:(c=screen,c=c.width/c.height,c=2<=Q(["MediaSource"in window,!!Element.prototype.webkitRequestFullscreen,c>2/3&&1.5>c])),c=c?"iPad":"iPhone");P(b,9,c)}
function zb(b){var c=[];for(var d=t("chrome safari __crWeb __gCrWeb yandex __yb __ybro __firefox__ __edgeTrackingPreventionStatistics webkit oprt samsungAr ucweb UCShellJava puffinDevice".split(" ")),e=d.next();!e.done;e=d.next()){e=e.value;var g=window[e];g&&"object"===typeof g&&c.push(e)}c=c.sort();P(b,13,c||[])}function Ab(b){try{var c=!!window.localStorage}catch(d){c=!0}P(b,31,c)}function Bb(b){try{var c=!!window.sessionStorage}catch(d){c=!0}P(b,32,c)}
function Cb(b){var c=document;try{c.cookie="cookietest=1; SameSite=Strict;";var d=-1!==c.cookie.indexOf("cookietest=");c.cookie="cookietest=1; SameSite=Strict; expires=Thu, 01-Jan-1970 00:00:01 GMT";var e=d}catch(g){e=!1}P(b,48,e)}
function Db(b){var c={acos:Eb(.12312423423423424),acosh:Fb(1E308),S:R.log(1E154+R.sqrt(1E154*1E154-1)),asin:Gb(.12312423423423424),asinh:Hb(1),T:R.log(1+R.sqrt(2)),atanh:Ib(.5),U:R.log(3)/2,atan:Kb(.5),sin:Lb(-1E300),sinh:Mb(1),aa:R.exp(1)-1/R.exp(1)/2,cos:Nb(10.000000000123),cosh:Ob(1),V:(R.exp(1)+1/R.exp(1))/2,tan:Pb(-1E300),tanh:Qb(1),da:(R.exp(2)-1)/(R.exp(2)+1),exp:Rb(1),expm1:Sb(1),W:R.exp(1)-1,log1p:Tb(10),X:R.log(11),Z:R.pow(R.PI,-100)};var d="",e;for(e in c)d+=e+"="+c[e]+",";c=S(d);P(b,50,
c)};function Ub(b,c){var d=void 0;return new (d||(d=Promise))(function(e,g){function h(n){try{q(c.next(n))}catch(r){g(r)}}function m(n){try{q(c["throw"](n))}catch(r){g(r)}}function q(n){n.done?e(n.value):(new d(function(r){r(n.value)})).then(h,m)}q((c=c.apply(b,void 0)).next())})};function Vb(b,c){return"number"===typeof b&&isNaN(b)?c:b}function Q(b){return b.reduce(function(c,d){return c+(d?1:0)},0)}
function Wb(b){function c(r,w){m[r]=m[r]||[];m[r].push(w)}var d,e,g="Unexpected syntax '"+b+"'";b=/^\s*([a-z-]*)(.*)$/i.exec(b);for(var h=b[1]||void 0,m={},q=/([.:#][\w-]+|\[.+?\])/gi;;){var n=q.exec(b[2]);if(!n)break;n=n[0];switch(n[0]){case ".":c("class",n.slice(1));break;case "#":c("id",n.slice(1));break;case "[":if(n=/^\[([\w-]+)([~|^$*]?=("(.*?)"|([\w-]+)))?(\s+[is])?\]$/.exec(n))c(n[1],null!==(e=null!==(d=n[4])&&void 0!==d?d:n[5])&&void 0!==e?e:"");else throw Error(g);break;default:throw Error(g);
}}return[h,m]};function Xb(){var b=window,c=navigator;return 4<=Q(["MSCSSMatrix"in b,"msSetImmediate"in b,"msIndexedDB"in b,"msMaxTouchPoints"in c,"msPointerEnabled"in c])}function Yb(){var b=window,c=navigator;return 3<=Q(["msWriteProfilerMark"in b,"MSStream"in b,"msLaunchUri"in c,"msSaveBlob"in c])&&!Xb()}
function Zb(){var b=window,c=navigator;return 5<=Q(["webkitPersistentStorage"in c,"webkitTemporaryStorage"in c,0===c.vendor.indexOf("Google"),"webkitResolveLocalFileSystemURL"in b,"BatteryManager"in b,"webkitMediaStream"in b,"webkitSpeechGrammar"in b])}function xb(){var b=window,c=navigator;return 4<=Q(["ApplePayError"in b,"CSSPrimitiveValue"in b,"Counter"in b,0===c.vendor.indexOf("Apple"),"getStorageUpdates"in c,"WebKitMediaKeys"in b])}
function yb(){var b=window;return 3<=Q(["safari"in b,!("DeviceMotionEvent"in b),!("ongestureend"in b),!("standalone"in navigator)])}
function $b(){var b=Zb(),c,d;var e=window;e=4<=Q(["buildID"in navigator,"MozAppearance"in(null!==(d=null===(c=document.documentElement)||void 0===c?void 0:c.style)&&void 0!==d?d:{}),"MediaRecorderErrorEvent"in e,"mozInnerScreenX"in e,"CSSMozDocumentRule"in e,"CanvasCaptureMediaStream"in e]);if(!b&&!e)return!1;c=window;return 2<=Q(["onorientationchange"in c,"orientation"in c,b&&"SharedWorker"in c,e&&/android/i.test(navigator.appVersion)])};function ac(b,c){b=[b[0]>>>16,b[0]&65535,b[1]>>>16,b[1]&65535];c=[c[0]>>>16,c[0]&65535,c[1]>>>16,c[1]&65535];var d=[0,0,0,0];d[3]+=b[3]+c[3];d[2]+=d[3]>>>16;d[3]&=65535;d[2]+=b[2]+c[2];d[1]+=d[2]>>>16;d[2]&=65535;d[1]+=b[1]+c[1];d[0]+=d[1]>>>16;d[1]&=65535;d[0]+=b[0]+c[0];d[0]&=65535;return[d[0]<<16|d[1],d[2]<<16|d[3]]}
function T(b,c){b=[b[0]>>>16,b[0]&65535,b[1]>>>16,b[1]&65535];c=[c[0]>>>16,c[0]&65535,c[1]>>>16,c[1]&65535];var d=[0,0,0,0];d[3]+=b[3]*c[3];d[2]+=d[3]>>>16;d[3]&=65535;d[2]+=b[2]*c[3];d[1]+=d[2]>>>16;d[2]&=65535;d[2]+=b[3]*c[2];d[1]+=d[2]>>>16;d[2]&=65535;d[1]+=b[1]*c[3];d[0]+=d[1]>>>16;d[1]&=65535;d[1]+=b[2]*c[2];d[0]+=d[1]>>>16;d[1]&=65535;d[1]+=b[3]*c[1];d[0]+=d[1]>>>16;d[1]&=65535;d[0]+=b[0]*c[3]+b[1]*c[2]+b[2]*c[1]+b[3]*c[0];d[0]&=65535;return[d[0]<<16|d[1],d[2]<<16|d[3]]}
function bc(b,c){c%=64;if(32===c)return[b[1],b[0]];if(32>c)return[b[0]<<c|b[1]>>>32-c,b[1]<<c|b[0]>>>32-c];c-=32;return[b[1]<<c|b[0]>>>32-c,b[0]<<c|b[1]>>>32-c]}function V(b,c){c%=64;return 0===c?b:32>c?[b[0]<<c|b[1]>>>32-c,b[1]<<c]:[b[1]<<c-32,0]}function W(b,c){return[b[0]^c[0],b[1]^c[1]]}function cc(b){b=W(b,[0,b[0]>>>1]);b=T(b,[4283543511,3981806797]);b=W(b,[0,b[0]>>>1]);b=T(b,[3301882366,444984403]);return b=W(b,[0,b[0]>>>1])}
function S(b){b=b||"";var c=c||0;var d=b.length%16,e=b.length-d,g=[0,c];c=[0,c];var h=[2277735313,289559509],m=[1291169091,658871167],q;for(q=0;q<e;q+=16){var n=[b.charCodeAt(q+4)&255|(b.charCodeAt(q+5)&255)<<8|(b.charCodeAt(q+6)&255)<<16|(b.charCodeAt(q+7)&255)<<24,b.charCodeAt(q)&255|(b.charCodeAt(q+1)&255)<<8|(b.charCodeAt(q+2)&255)<<16|(b.charCodeAt(q+3)&255)<<24];var r=[b.charCodeAt(q+12)&255|(b.charCodeAt(q+13)&255)<<8|(b.charCodeAt(q+14)&255)<<16|(b.charCodeAt(q+15)&255)<<24,b.charCodeAt(q+
8)&255|(b.charCodeAt(q+9)&255)<<8|(b.charCodeAt(q+10)&255)<<16|(b.charCodeAt(q+11)&255)<<24];n=T(n,h);n=bc(n,31);n=T(n,m);g=W(g,n);g=bc(g,27);g=ac(g,c);g=ac(T(g,[0,5]),[0,1390208809]);r=T(r,m);r=bc(r,33);r=T(r,h);c=W(c,r);c=bc(c,31);c=ac(c,g);c=ac(T(c,[0,5]),[0,944331445])}n=[0,0];r=[0,0];switch(d){case 15:r=W(r,V([0,b.charCodeAt(q+14)],48));case 14:r=W(r,V([0,b.charCodeAt(q+13)],40));case 13:r=W(r,V([0,b.charCodeAt(q+12)],32));case 12:r=W(r,V([0,b.charCodeAt(q+11)],24));case 11:r=W(r,V([0,b.charCodeAt(q+
10)],16));case 10:r=W(r,V([0,b.charCodeAt(q+9)],8));case 9:r=W(r,[0,b.charCodeAt(q+8)]),r=T(r,m),r=bc(r,33),r=T(r,h),c=W(c,r);case 8:n=W(n,V([0,b.charCodeAt(q+7)],56));case 7:n=W(n,V([0,b.charCodeAt(q+6)],48));case 6:n=W(n,V([0,b.charCodeAt(q+5)],40));case 5:n=W(n,V([0,b.charCodeAt(q+4)],32));case 4:n=W(n,V([0,b.charCodeAt(q+3)],24));case 3:n=W(n,V([0,b.charCodeAt(q+2)],16));case 2:n=W(n,V([0,b.charCodeAt(q+1)],8));case 1:n=W(n,[0,b.charCodeAt(q)]),n=T(n,h),n=bc(n,31),n=T(n,m),g=W(g,n)}g=W(g,[0,b.length]);
c=W(c,[0,b.length]);g=ac(g,c);c=ac(c,g);g=cc(g);c=cc(c);g=ac(g,c);c=ac(c,g);b=new ArrayBuffer(16);d=new DataView(b);d.setInt32(0,g[0],!0);d.setInt32(4,g[1],!0);d.setInt32(8,c[0],!0);d.setInt32(12,c[1],!0);return new Uint8Array(b)};function dc(){return Ub(this,function c(){var d,e,g,h,m,q,n,r;return B(c,function(w){switch(w.a){case 1:d=window;e=d.OfflineAudioContext||d.webkitOfflineAudioContext;if(!e)return w.return(S(-(2).toString()));var x;if(x=xb()&&!yb())x=window,x=!(3<=Q(["DOMRectList"in x,"RTCPeerConnectionIceEvent"in x,"SVGGeometryElement"in x,"ontransitioncancel"in x]));if(x)return w.return(S(-(1).toString()));g=4500;h=new e(1,5E3,44100);m=h.createOscillator();m.type="triangle";m.frequency.value=1E4;q=h.createDynamicsCompressor();
q.threshold.value=-50;q.knee.value=40;q.ratio.value=12;q.attack.value=0;q.release.value=.25;m.connect(q);q.connect(h.destination);m.start(0);w.f=2;return u(w,ec(h),4);case 4:n=w.c;w.a=3;w.f=0;break;case 2:r=sa(w);if("timeout"===r.name||"suspended"===r.name)return w.return(S(-(3).toString()));throw r;case 3:return w.return(fc(n.getChannelData(0).subarray(g)))}})})}
function ec(b){return new Promise(function(c,d){function e(){b.startRendering();switch(b.state){case "running":setTimeout(function(){return d(gc("timeout"))},1E3);break;case "suspended":document.hidden||g--,0<g?setTimeout(e,500):d(gc("suspended"))}}b.oncomplete=function(h){return c(h.renderedBuffer)};var g=3;e()})}function fc(b){for(var c="",d=0;d<b.length;++d)c+=b[d].toString()+",";return S(c)}function gc(b){var c=Error(b);c.name=b;return c};function hc(b){function c(h){return 26>h?65+h:52>h?71+h:62>h?h-4:62==h?43:47}var d="",e=0;for(e=0;e+2<b.length;e+=3){var g=b[e]<<16|b[e+1]<<8|b[e+2];d+=String.fromCharCode(c(g>>18&63),c(g>>12&63),c(g>>6&63),c(g&63))}e+1<b.length?(b=b[e]<<8|b[e+1],d+=String.fromCharCode(c(b>>10&63),c(b>>4&63),c(b<<2&63),61)):e<b.length&&(b=b[e],d+=String.fromCharCode(c(b>>2&63),c(b<<4&63),61,61));return d};function ic(){var b=document.createElement("canvas");b.width=1;b.height=1;b=[b,b.getContext("2d")];var c=t(b);b=c.next().value;var d=c.next().value;if(d&&b.toDataURL){d.rect(0,0,10,10);d.rect(2,2,6,6);c=!d.isPointInPath(5,5,"evenodd");b.width=122;b.height=110;d.globalCompositeOperation="multiply";var e=t([["#f2f",40,40],["#2ff",80,40],["#ff2",60,80]]);for(var g=e.next();!g.done;g=e.next()){var h=t(g.value);g=h.next().value;var m=h.next().value;h=h.next().value;d.fillStyle=g;d.beginPath();d.arc(m,
h,40,0,2*Math.PI,!0);d.closePath();d.fill()}d.fillStyle="#f9c";d.arc(60,60,60,0,2*Math.PI,!0);d.arc(60,60,20,0,2*Math.PI,!0);d.fill("evenodd");e=b.toDataURL();e=S(e);b.width=240;b.height=60;d.textBaseline="alphabetic";d.fillStyle="#f60";d.fillRect(100,1,62,20);d.fillStyle="#069";d.font='11pt "Times New Roman"';g="Cwm fjordbank gly "+String.fromCharCode(55357,56835);d.fillText(g,2,15);d.fillStyle="rgba(102, 204, 0, 0.2)";d.font="18pt Arial";d.fillText(g,4,45);b=b.toDataURL();b={C:c,A:e,text:S(b)}}else b=
{C:!1,A:new Uint8Array(16),text:new Uint8Array(16)};return b};function jc(){for(var b=t(["rec2020","p3","srgb"]),c=b.next();!c.done;c=b.next())if(c=c.value,window.matchMedia("(color-gamut: "+c+")").matches)return c};function kc(){if(lc("no-preference"))return 1;if(lc("high")||lc("more"))return 2;if(lc("low")||lc("less"))return 0;if(lc("forced"))return 10}function lc(b){return window.matchMedia("(prefers-contrast: "+b+")").matches};function mc(b){return("00"+b.toString(16)).slice(-2)};function nc(){var b="";try{b="{{ profiling.webrtc_domain }}"}catch(c){}return b}function oc(){var b=dwn_ns.dwn_log("main"),c=!1;try{"boolean"===typeof {% if profiling.javascript.disabled_features | contains("geo_location") %}false{% else %}true{% endif %}?c={% if profiling.javascript.disabled_features | contains("geo_location") %}false{% else %}true{% endif %}:"boolean"===typeof dwn_ns.geo_location_enabled&&(c=dwn_ns.geo_location_enabled)}catch(d){c=!0}b("isGeoLocationEnabled",c);return c}
function pc(b){var c=dwn_ns.dwn_log("main"),d=[],e=null;try{d=[{% for domain in profiling.javascript.request_domains %} "{{ domain | split("/") | first }}", {% endfor %}],e=(new URL(b)).hostname}catch(h){}try{if(!e)return c("isValidRequestDomain can't find hostname in url: "+b),!0;if(e===window.location.hostname)return c("isValidRequestDomain has same hostname as window.location: "+b),!0;for(var g=0;g<d.length;g++)if(c("valid domain: "+d[g]),e===d[g])return c("isValidRequestDomain matched on one of preset domains: "+b),!0}catch(h){}c("isValidRequestDomain invalid request hostname: "+
b);return!1};var Y=dwn_ns.dwn_log("crypto"),qc=window.crypto||window.msCrypto,rc="undefined"!==typeof qc?qc.subtle||qc.ga:null;
function sc(b){return new Promise(function(c,d){try{var e=b.open("dwn_db_3lkbmv5",1),g=!1;e.onupgradeneeded=function(h){Y("onupgradeneeded triggered");g=!0;var m=h.target.result;m.createObjectStore("dwn_db_3lkbmv5",{keyPath:"id"}).transaction.oncomplete=function(){var q=rc.generateKey({name:"ECDSA",namedCurve:"P-256"},!1,["sign"]);if("undefined"===typeof q)return d("Failed to subtle.generateKey");q.then(function(n){try{if("undefined"!==typeof n){Y("Generated keypair: ",n);var r=m.transaction("dwn_db_3lkbmv5",
"readwrite").objectStore("dwn_db_3lkbmv5"),w=Math.floor(Date.now()/1E3),x=n.privateKey,z=n.publicKey,E=r.add({id:"dwn_db_3lkbmv5",publicKey:z,privateKey:x,G:w});E.onsuccess=function(){Y("Add store onsuccess, createTime:"+w);c([w,x,z])};E.onerror=function(L){d("Add store failed onerror: "+L)}}else d("Failed to get in result.then")}catch(L){d("generateKey result.then failed: "+L)}},function(n){d("createCryptoKeyPair result.then failed: "+n)})}};e.onsuccess=function(h){g||(h=h.target.result,Y("onsuccess triggered"),
h=h.transaction("dwn_db_3lkbmv5","readonly").objectStore("dwn_db_3lkbmv5").get("dwn_db_3lkbmv5"),h.onsuccess=function(m){try{var q=m.target.result,n=q.G,r=q.privateKey,w=q.publicKey;n&&r&&w?(Y("Get store onsuccess, createTime: ",n,r,w),c([n,r,w])):d("Get store succeed, but content is wrong: "+n)}catch(x){d("Get store succeed, catch error: "+x)}},h.onerror=function(m){d("Get store failed onerror: "+m)})};e.onerror=function(h){d("Failed on open indexedDB: "+h)}}catch(h){d("Failed on get_crypto_auth: "+
h)}setTimeout(function(){d("getDBStore timeout")},500)})}
function tc(b){return new Promise(function(c,d){try{var e=rc.exportKey("spki",b);e&&"undefined"!==typeof e||(Y("Failed to exportKey spki"),d("Failed to exportKey spki"));"undefined"!==typeof e.then?e.then(function(g){g=hc(new Uint8Array(g));Y("Got exportKey on ret.then: "+g);c(g)}).catch(function(g){throw g;}):e.oncomplete=function(g){if(g.target&&g.target.result)return g=hc(new Uint8Array(g.target.result)),Y("Got exportKey oncomplete: "+g),c(g);d("Empty event.targe")}}catch(g){Y("Can't export key: "+
g),d(g)}setTimeout(function(){c("timeout in export")},500)})}function uc(b,c,d){var e=[];b=b+c+d;Y("sign data: ["+b+"]");for(c=0;c<b.length;c++)e.push(b.charCodeAt(c));return new Uint8Array(e)}function vc(b){return("00"+(b.length/2).toString(16)).slice(-2).toString()}
function wc(b){try{var c=Array.prototype.map.call(new Uint8Array(b),mc).join(""),d=c.substring(0,c.length/2),e=c.substring(c.length/2);for(c=b=!0;0===d.indexOf("00");)d=d.substring(2),b=!1;for(b&&127<parseInt(d.substring(0,2),16)&&(d="00"+d);0===e.indexOf("00");)e=e.substring(2),c=!1;c&&127<parseInt(e.substring(0,2),16)&&(e="00"+e);var g="02"+vc(d)+d+"02"+vc(e)+e,h=("30"+vc(g)+g).match(/.{1,2}/g);if(h){var m=new Uint8Array(h.map(function(q){return parseInt(q,16)}));return hc(m)}}catch(q){Y("Failed to get signature: "+
q)}}
function xc(b,c,d){return new Promise(function(e,g){try{var h=b.algorithm.name,m=uc(h,c,d),q=rc.sign({name:h,hash:{name:"SHA-256"}},b,m);"undefined"!==typeof q.then?q.then(function(n){if(n=wc(n))Y("Got signature in ret.then: "+n),e(n);g("no signature")},function(n){Y("Failed to sign data: "+n);g(n)}).catch(function(n){throw n;}):q.oncomplete=function(n){if(n=wc(n.target.result))Y("Got signature oncomplete: "+n),e(n);g("no signature")}}catch(n){Y("signNonce: "+n),g(n)}setTimeout(function(){e("timeout in signNonce")},500)})}
function yc(){return Ub(this,function c(){var d,e,g,h,m,q,n,r,w;return B(c,function(x){switch(x.a){case 1:return x.f=2,d=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB||window.a,d&&qc&&rc?u(x,sc(d),4):(Y("Strong Auth not supported"),x.return(void 0));case 4:e=x.c;if(!e)return Y("getDBStore failed"),x.return();g=e[0];h=e[1];m=e[2];if(!h||!m){x.j(5);break}var z="";try{z="{{ profiling.browser_crypto.outgoing_nonce }}"}catch(E){}q=z;return u(x,tc(m),6);case 6:n=x.c;if(!n){x.j(5);break}return u(x,
xc(h,q,g),8);case 8:if(r=x.c)return x.return([g,n,r]);case 5:x.a=3;x.f=0;break;case 2:w=sa(x),Y("Failed on get_crypto catch: "+w);case 3:return Y("all done"),x.return(void 0)}})})};function zc(b){return new Promise(function(c){return setTimeout(c,b,void 0)})};function Ac(b,c){var d=void 0===d?50:d;var e,g;return Ub(this,function m(){var q,n;return B(m,function(r){switch(r.a){case 1:q=document;case 2:return q.body?(n=q.createElement("iframe"),ra(r),u(r,new Promise(function(w,x){function z(){var E;"complete"===(null===(E=n.contentWindow)||void 0===E?void 0:E.document.readyState)?w(null):setTimeout(z,10)}n.onload=w;n.onerror=x;x=n.style;x.setProperty("display","block","important");x.position="absolute";x.top="0";x.left="0";x.visibility="hidden";c&&"srcdoc"in
n?n.srcdoc=c:n.src="about:blank";q.body.appendChild(n);z()}),8)):u(r,zc(d),2);case 8:return(null===(e=n.contentWindow)||void 0===e?0:e.document.body)?u(r,b(n,n.contentWindow),11):u(r,zc(d),8);case 11:return r.return(r.c);case 5:ta(r),null===(g=n.parentNode)||void 0===g?void 0:g.removeChild(n),ua(r)}})})};var Bc=[{key:0,list:["#Iklan-Melayang","#Kolom-Iklan-728","#SidebarIklan-wrapper",'a[title="7naga poker" i]','[title="ALIENBOLA" i]']},{key:1,list:["#quangcaomb",".i-said-no-thing-can-stop-me-warning.dark",".quangcao",'[href^="https://r88.vn/"]','[href^="https://zbet.vn/"]']},{key:2,list:[".mainostila",".sponsorit",".ylamainos",'a[href*="/clickthrgh.asp?"]','a[href^="https://app.readpeak.com/ads"]']},{key:3,list:["#navbar_notice_50",'a[href^="https://iqoption.com/lp/mobile-partner/?aff="]',".kadr",
'TABLE[width="140px"]',"#divAgahi"]},{key:4,list:["#adblock_message",".adblockInfo",".deadblocker-header-bar",".no-ad-reminder","#AdBlockDialog"]},{key:5,list:['amp-embed[type="zen"]',".hs-sosyal","#cookieconsentdiv",'div[class^="app_gdpr"]',".as-oil"]},{key:6,list:["#gads_middle",".tjads",".BetterJsPopOverlay","#ad_300X250","#bannerfloat22"]},{key:7,list:['a[href*=".123ch.cn"]','a[href*=".ttz5.cn"]','a[href*=".yabovip2027.com/"]',".tm3all2h4b","#j-new-ad"]},{key:8,list:["#div_banniere_pub",'a[href^="https://secure.securitetotale.fr/"]',
'a[href*="fducks.com/"]','a[href^="http://frtyd.com/"]',".publicite1"]},{key:9,list:[".banneritemwerbung_head_1",".boxstartwerbung",".werbung3",'a[href^="http://www.ichwuerde.com/?ref="]','a[href^="http://partners.adklick.de/tracking.php?"]']},{key:10,list:[".ad-text-blockA01","._popIn_infinite_video","[class^=blogroll_wrapper]",'a[href^="http://ad2.trafficgate.net/"]','a[href^="http://www.rssad.jp/"]']},{key:11,list:["amp-auto-ads","#mgid_iframe",".amp_ad","amp-sticky-ad",".plugin-blogroll"]},{key:12,
list:['a[href^="https://ya-distrib.ru/r/"]','[onclick*=".twkv.ru"]',".reclama",'div[id^="smi2adblock"]','div[id^="AdFox_banner_"]']},{key:13,list:['a[href^="//www.stumbleupon.com/submit?url="]','a[href^="//telegram.me/share/url?"]',".etsy-tweet","#inlineShare",".popup-social"]},{key:14,list:["#barraPublicidade","#Publicidade","#publiEspecial","#queTooltip",'[href^="http://ads.glispa.com/"]']},{key:15,list:['amp-embed[type="taboola"]',"#qoo-counter",'a[href^="http://click.hotlog.ru/"]','a[href^="http://hitcounter.ru/top/stat.php"]',
'a[href^="http://top.mail.ru/jump"]']},{key:16,list:["#backkapat","#reklami",'a[href^="http://adserv.ontek.com.tr/"]','a[href^="http://izlenzi.com/campaign/"]','a[href^="http://www.installads.net/"]']},{key:17,list:["td#freenet_table_ads","#newAd","#ea_intext_div",".lapni-pop-over","#xenium_hot_offers"]},{key:18,list:['[lazy-ad="leftthin_banner"]',"#ad_300x250_2","#interstitialAd","#wide_ad_unit",".showcaseAd"]},{key:19,list:['a[href*=".wensixuetang.com/"]','A[href*="/hth107.com/"]','.appguide-wrap[onclick*="bcebos.com"]',
".frontpageAdvM","#taotaole"]},{key:20,list:["#CookieEU","#__cookies_","#les_cookies",".asset_balaNotification",".gdpr-tab"]},{key:21,list:["#onlajny-stickers","#reklamni-box",".reklama-megaboard",".sklik",'[id^="sklikReklama"]']},{key:22,list:["#advertentie","#vipAdmarktBannerBlock",".adstekst",'a[href^="http://adserver.webads.nl/adclick/"]',"#semilo-lrectangle"]},{key:23,list:["#LxWerbeteaser",'a[href^="http://www.kontakt-vermittler.de/?wm="]',".werbung301",".ads_bueroklammer","#Werbung_Sky"]},
{key:24,list:[".box_adv_annunci",".sb-box-pubbliredazionale",'a[href^="http://affiliazioniads.snai.it/"]','a[href^="https://adserver.html.it/"]','a[href^="https://affiliazioniads.snai.it/"]']},{key:25,list:[".reklamos_tarpas",".reklamos_nuorodos",'img[alt="Reklaminis skydelis"]','img[alt="Dedikuoti.lt serveriai"]','img[alt="Hostingas Serveriai.lt"]']},{key:26,list:['A[href*="http://pay4results24.eu"]']},{key:27,list:["#feedback-tab","#taboola-below-article",".feedburnerFeedBlock",".widget-feedburner-counter",
'[title="Subscribe to our blog"]']},{key:28,list:[".util-bar-module-firefly-visible"]},{key:29,list:[".open.pushModal","#issuem-leaky-paywall-articles-zero-remaining-nag",'div[style*="box-shadow: rgb(136, 136, 136) 0px 0px 12px; color: "]','div[class$="-hide"][zoompage-fontsize][style="display: block;"]',".BlockNag__Card"]},{key:30,list:[".td-tags-and-social-wrapper-box",".twitterContainer",".youtube-social",'a[title^="Like us on Facebook"]','img[alt^="Share on Digg"]']},{key:31,list:['a[href*="casinopro.se"][target="_blank"]',
'a[href*="doktor-se.onelink.me"]',"article.category-samarbete","div.holidAds","ul.adsmodern"]},{key:32,list:['A[href*="adman.otenet.gr/click?"]','A[href*="http://axiabanners.exodus.gr/"]','A[href*="http://interactive.forthnet.gr/click?"]',"DIV.agores300","TABLE.advright"]},{key:33,list:['A[href*="ad.eval.hu"]','A[href*="ad.netmedia.hu"]','A[href*="daserver.ultraweb.hu"]',"#cemp_doboz",".optimonk-iframe-container"]},{key:34,list:['.alert-info[data-block-track*="CookieNotice"]',".ModuleTemplateCookieIndicator",
".o--cookies--container",".cookie-msg-info-container","#cookies-policy-sticky"]},{key:35,list:['A[href^="/framework/resources/forms/ads.aspx"]']},{key:36,list:['a[href="http://www.salidzini.lv/"][style="display: block; width: 120px; height: 40px; overflow: hidden; position: relative;"]','a[href="http://www.salidzini.lv/"][style="display: block; width: 88px; height: 31px; overflow: hidden; position: relative;"]']},{key:37,list:['a[href*="//kingtoon.slnk.kr"]','a[href*="//playdsb.com/kr"]',"div.logly-lift-adz",
'div[data-widget_id="ml6EJ074"]',"ins.daum_ddn_area"]},{key:38,list:[".geminiLB1Ad",".right-and-left-sponsers",'a[href*=".aflam.info"]','a[href*="booraq.org"]','a[href*="dubizzle.com/ar/?utm_source="]']},{key:39,list:['a[href^="http://promo.vador.com/"]',"#adcontainer_recherche",'a[href*="weborama.fr/fcgi-bin/"]',".site-pub-interstitiel",'div[id^="crt-"][data-criteo-id]']},{key:40,list:["#ceneo-placeholder-ceneo-12",'[href^="https://aff.sendhub.pl/"]','a[href^="http://advmanager.techfun.pl/redirect/"]',
'a[href^="http://www.trizer.pl/?utm_source"]',"div#skapiec_ad"]},{key:41,list:['a[href^="//afftrk.altex.ro/Counter/Click"]','a[href^="/magazin/"]','a[href^="https://blackfridaysales.ro/trk/shop/"]','a[href^="https://event.2performant.com/events/click"]','a[href^="https://l.profitshare.ro/"]']},{key:42,list:['a[href*="//febrare.ru/"]','a[href*="//utimg.ru/"]','a[href*="://chikidiki.ru"]',"#pgeldiz",".yandex-rtb-block"]},{key:43,list:["a[href*=macau-uta-popup]","#ads-google-middle_rectangle-group",
".ads300s",".bumq",".img-kosana"]},{key:44,list:["#mod-social-share-2","#social-tools",".ctpl-fullbanner",".zergnet-recommend",".yt.btn-link.btn-md.btn"]}];
function Cc(){var b={}.debug;return Ub(this,function d(){var e,g,h,m,q,n,r,w;return B(d,function(x){if(1==x.a){if(!xb()&&!$b())return x.return(void 0);e=[].concat.apply([],ba(Bc.map(function(z){return z.list})));return u(x,Dc(e),2)}g=x.c;b&&Ec(g);h=[];m=t(Bc);for(q=m.next();!q.done;q=m.next())n=q.value,r=n.list,w=Q(r.map(function(z){return g[z]})),w>.5*r.length&&h.push(n.key);return x.return(h)})})}
function Dc(b){var c;return Ub(this,function e(){var g,h,m,q,n,r,w,x,z,E;return B(e,function(L){if(1==L.a)for(g=document,h=g.createElement("div"),m=[],q={},Fc(h),n=t(b),r=n.next();!r.done;r=n.next()){w=r.value;var C=t(Wb(w)),X=C.next().value;C=C.next().value;X=document.createElement(null!==X&&void 0!==X?X:"div");for(var Fa=t(Object.keys(C)),ea=Fa.next();!ea.done;ea=Fa.next())ea=ea.value,X.setAttribute(ea,C[ea].join(" "));x=X;z=g.createElement("div");Fc(z);z.appendChild(x);h.appendChild(z);m.push(x)}if(3!=
L.a)return g.body?L.j(3):u(L,zc(50),2);g.body.appendChild(h);try{for(E=0;E<b.length;++E)m[E].offsetParent||(q[b[E]]=!0)}finally{null===(c=h.parentNode)||void 0===c?void 0:c.removeChild(h)}return L.return(q)})})}function Fc(b){b.style.setProperty("display","block","important")}
function Ec(b){for(var c="DOM blockers debug:\n```",d=t(Bc),e=d.next();!e.done;e=d.next()){e=e.value;c+="\n"+e.key+":";e=t(e.list);for(var g=e.next();!g.done;g=e.next())g=g.value,c+="\n  "+g+" "+(b[g]?"\ud83d\udeab":"\u27a1\ufe0f")}console.log(c+"\n```")};var Gc={default:[],F:[{font:"-apple-system-body"}],M:[{fontFamily:"serif"}],L:[{fontFamily:"sans-serif"}],H:[{fontFamily:"monospace"}],min:[{fontSize:"1px"}],N:[{fontFamily:"system-ui"}]};
function Hc(){return Ic(function(b,c){for(var d={},e={},g=t(Object.keys(Gc)),h=g.next();!h.done;h=g.next()){h=h.value;var m=t(Gc[h]),q=m.next().value;q=void 0===q?{}:q;var n=m.next().value;m=b.createElement("span");m.textContent=void 0===n?"mmMwWLliI0fiflO&1":n;m.style.whiteSpace="nowrap";n=t(Object.keys(q));for(var r=n.next();!r.done;r=n.next()){r=r.value;var w=q[r];void 0!==w&&(m.style[r]=w)}d[h]=m;c.appendChild(b.createElement("br"));c.appendChild(m)}b=t(Object.keys(Gc));for(h=b.next();!h.done;h=
b.next())c=h.value,e[c]=d[c].getBoundingClientRect().width;return e})}
function Ic(b){var c=void 0===c?4E3:c;return Ac(function(d,e){d=e.document;var g=d.body,h=g.style;h.width=c+"px";h.webkitTextSizeAdjust=h.ea="none";Zb()?g.style.zoom=""+1/e.devicePixelRatio:xb()&&(g.style.zoom="reset");e=d.createElement("div");e.textContent=ba(Array(c/20<<0)).concat().map(function(){return"word"}).join(" ");g.appendChild(e);return b(d,g)},'<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1">')};var Jc=["monospace","sans-serif","serif"],Kc="sans-serif-thin;ARNO PRO;Agency FB;Arabic Typesetting;Arial Unicode MS;AvantGarde Bk BT;BankGothic Md BT;Batang;Bitstream Vera Sans Mono;Calibri;Century;Century Gothic;Clarendon;EUROSTILE;Franklin Gothic;Futura Bk BT;Futura Md BT;GOTHAM;Gill Sans;HELV;Haettenschweiler;Helvetica Neue;Humanst521 BT;Leelawadee;Letter Gothic;Levenim MT;Lucida Bright;Lucida Sans;Menlo;MS Mincho;MS Outlook;MS Reference Specialty;MS UI Gothic;MT Extra;MYRIAD PRO;Marlett;Meiryo UI;Microsoft Uighur;Minion Pro;Monotype Corsiva;PMingLiU;Pristina;SCRIPTINA;Segoe UI Light;Serifa;SimHei;Small Fonts;Staccato222 BT;TRAJAN PRO;Univers CE 55 Medium;Vrinda;ZWAdobeF".split(";");
function Lc(){return Ac(function(b,c){function d(r){return Jc.some(function(w,x){return r[x].offsetWidth!==m[w]||r[x].offsetHeight!==q[w]})}function e(r){var w=g.createElement("span"),x=w.style;x.position="absolute";x.top="0";x.left="0";x.fontFamily=r;w.textContent="mmMwWLliI0O&1";h.appendChild(w);return w}var g=c.document;c=g.body;c.style.fontSize="48px";var h=g.createElement("div"),m={},q={};b=Jc.map(e);var n=function(){for(var r={},w={},x=t(Kc),z=x.next();!z.done;w={o:w.o},z=x.next())w.o=z.value,
r[w.o]=Jc.map(function(E){return function(L){return e("'"+E.o+"',"+L)}}(w));return r}();c.appendChild(h);for(c=0;c<Jc.length;c++)m[Jc[c]]=b[c].offsetWidth,q[Jc[c]]=b[c].offsetHeight;if((b=Kc.filter(function(r){return d(n[r])}))&&0!==b.length)return[b.length,S(b.sort().toString())]})};function Mc(){return new Promise(function(b,c){try{var d=function(e){b([e.coords.latitude,e.coords.longitude,e.coords.accuracy])};if("https:"!==location.protocol)return c(void 0);navigator.geolocation&&navigator.geolocation.getCurrentPosition(d)}catch(e){c(void 0)}})};function Nc(){if(window.matchMedia("(dynamic-range: high)").matches)return!0;if(window.matchMedia("(dynamic-range: standard)").matches)return!1};function Oc(b){return window.matchMedia("(inverted-colors: "+b+")").matches};function Pc(){var b=navigator,c=b.language||b.fa||b.browserLanguage||b.ca,d=[];if(Array.isArray(b.languages)){var e;(e=!Zb())||(e=window,e=!(3<=Q([!("MediaSettingsRange"in e),"RTCEncodedAudioFrame"in e,"[object Intl]"===""+e.Intl,"[object Reflect]"===""+e.Reflect])));e&&(d=b.languages)}else"string"===typeof b.languages&&(b=b.languages)&&(d=b.split(","));return[c,d]};var R=Math;function Z(){return 0}var Eb=R.acos||Z,Fb=R.acosh||Z,Gb=R.asin||Z,Hb=R.asinh||Z,Ib=R.atanh||Z,Kb=R.atan||Z,Lb=R.sin||Z,Mb=R.sinh||Z,Nb=R.cos||Z,Ob=R.cosh||Z,Pb=R.tan||Z,Qb=R.tanh||Z,Rb=R.exp||Z,Sb=R.expm1||Z,Tb=R.log1p||Z;function Qc(){if(window.matchMedia("(min-monochrome: 0)").matches){for(var b=0;100>=b;++b)if(window.matchMedia("(max-monochrome: "+b+")").matches)return b;throw Error("Too high value");}};function Rc(){var b=navigator.plugins;if(!b)return[];for(var c="",d=0,e=0;e<b.length;++e){var g=b[e];if(g){d+=1;c+=g.name+","+g.description+",";for(var h=0;h<g.length;++h){var m=g[h];c+=m.type+","+m.suffixes+","}}}return 0===d?[]:[d,S(c)]};function Sc(b){return window.matchMedia("(prefers-reduced-motion: "+b+")").matches};var Tc;function Uc(){return Ub(this,function c(){var d;return B(c,function(e){if(1==e.a){d=Vc();if(Wc(d))if(Tc)e=e.return(ba(Tc).concat());else{var g=document;g.fullscreenElement||g.msFullscreenElement||g.mozFullScreenElement||g.webkitFullscreenElement?(g=document,g=(g.exitFullscreen||g.msExitFullscreen||g.mozCancelFullScreen||g.webkitExitFullscreen).call(g),e=u(e,g,4)):e=e.j(2)}else e=e.j(2);return e}2!=e.a&&(d=Vc());Wc(d)||(Tc=d);return e.return(d)})})}
function Xc(){return Ub(this,function c(){var d,e;return B(c,function(g){if(1==g.a)return d=function(h){if(null===h)h=null;else{var m=10;m=void 0===m?1:m;1<=Math.abs(m)?h=Math.round(h/m)*m:(m=1/m,h=Math.round(h*m)/m)}return h},u(g,Uc(),2);e=g.c;return g.return([d(e[0]),d(e[1]),d(e[2]),d(e[3])])})})}
function Vc(){var b=screen;return[Vb(parseFloat(b.availTop),null),Vb(parseFloat(b.width)-parseFloat(b.availWidth)-Vb(parseFloat(b.availLeft),0),null),Vb(parseFloat(b.height)-parseFloat(b.availHeight)-Vb(parseFloat(b.availTop),0),null),Vb(parseFloat(b.availLeft),null)]}function Wc(b){for(var c=0;4>c;++c)if(b[c])return!1;return!0};function Yc(){var b=screen;b=[parseInt(b.width),parseInt(b.height)];b.sort(function(c,d){return d-c});return b};function Zc(){var b,c=null===(b=window.Intl)||void 0===b?void 0:b.DateTimeFormat;if(c)var d=(new c).resolvedOptions().timeZone;c=(new Date).getFullYear();b=(new Date(c,0,1)).getTimezoneOffset();c=(new Date(c,6,1)).getTimezoneOffset();!d&&b&&c&&(d=-Math.max(b,c),d="UTC"+(0<=d?"+":"")+Math.abs(d));return[d,b,c]};function $c(){var b=navigator,c=0;void 0!==b.maxTouchPoints?c=parseInt(b.maxTouchPoints):void 0!==b.msMaxTouchPoints&&(c=b.msMaxTouchPoints);try{document.createEvent("TouchEvent");var d=!0}catch(e){d=!1}return{maxTouchPoints:c,O:d,P:"ontouchstart"in window}};function ad(){try{a:{if(window.WebGLRenderingContext)for(var b=document.createElement("canvas"),c=["webgl","experimental-webgl","moz-webgl","webkit-3d"],d=0;4>d;d++)try{var e=b.getContext(c[d]);if(e&&"function"===typeof e.getParameter&&"function"===typeof e.getExtension){var g=e;break a}}catch(n){}g=void 0}if(g){c=b=void 0;var h=g.getExtension("WEBGL_debug_renderer_info");if(h&&"object"===typeof h){var m=g.getParameter(h.UNMASKED_VENDOR_WEBGL);"string"===typeof m&&(c=m);var q=g.getParameter(h.UNMASKED_RENDERER_WEBGL);
"string"===typeof q&&(b=q);return[b,c]}}}catch(n){}};function bd(b,c,d){return new Promise(function(e,g){var h=dwn_ns.dwn_log("webrtc"),m=window,q=!1,n=[];"tcp"!==d&&"udp"!==d&&g("failed");var r={iceServers:[{urls:"turn:"+c+"?transport="+d,username:b,credential:"darwinium"}]},w=null;try{w=new (m.RTCPeerConnection||m.I||m.webkitRTCPeerConnection)(r);w.onicecandidate=function(z){if(z.candidate&&z.candidate.candidate&&(z=z.candidate.candidate,h("candidate",z),(z=z.substr(z.indexOf("candidate:")+10).split(" "))&&!(7>=z.length)&&z[4])){var E=z[4];E=/([0-9]{1,3}(\.[0-9]{1,3}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7})/.exec(E);
!Array.isArray(E)||1>=E.length||(E=E[1],"host"!==z[7]&&"prflx"!==z[7]?q=!0:"host"===z[7]&&-1===n.indexOf(E)&&n.push(E))}};w.onicegatheringstatechange=function(){null!==w&&"complete"===w.iceGatheringState&&(w.close(),e([q,n]))};w.createDataChannel(Math.random().toString());var x=function(){};m=function(z){w.setLocalDescription(z,x,x)};"undefined"===typeof Promise||0<w.createOffer.length?w.createOffer(m,x):w.createOffer().then(m,x);setTimeout(function(){w.close();e([q,n])},2E3)}catch(z){w&&w.close(),
g(z)}})}
function cd(){var b=dd,c=nc();return Ub(this,function e(){var g,h;return B(e,function(m){switch(m.a){case 1:g=dwn_ns.dwn_log("webrtc");if(c&&0<c.length)g("webrtc connect on domain",c);else return g("No webrtc domain set"),m.return(void 0);m.f=2;var q=window;return(q=q.RTCPeerConnection||q.I||q.webkitRTCPeerConnection)&&"undefined"!==typeof q?u(m,bd(b,c,"tcp"),4):m.return([!1]);case 4:if((h=m.c)&&0!==h.length&&h[0]){m.j(5);break}return u(m,bd(b,c,"udp"),6);case 6:h=m.c;case 5:return h&&h[1]&&0<h[1].length?
m.return([!0,h[1].sort().join()]):m.return([!0]);case 2:sa(m);case 3:return m.return(void 0)}})})};var ed="";try{ed="{{ profiling.outgoing_handle }}"}catch(b){var fd="lower";fd=void 0===fd?"all":fd;var gd="",hd=62;"hex"===fd?hd=16:"lower"===fd&&(hd=36);for(var id=0;32>id;id++)gd+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(Math.random()*hd));ed=gd}var dd=ed;dwn_ns=dwn_ns||{};var jd=window.onload;
window.onload=function(b){function c(p,k,f){if("undefined"!==typeof p[k+"_min"]){var l=new fb;P(l,1,f);P(l,2,p[k+"_min"]);P(l,3,p[k+"_max"]);P(l,5,p[k+"_mad"]);P(l,4,p[k+"_avg"]);P(l,6,p[k+"_median"]);P(l,7,p[k+"_std_dev"]);return l}}function d(p){if("undefined"===typeof dwn_ns.field_bm)C("No field_bm at all");else{for(var k=[],f=t(Object.entries(dwn_ns.field_bm)),l=f.next();!l.done;l=f.next()){l=t(l.value);var D=l.next().value;l=l.next().value.getKeyRecords();C("setFieldBM",D,l);var v=new gb;P(v,
1,D.toLowerCase());P(v,3,l.type);P(v,4,l.name);P(v,5,l.id);P(v,10,l.focus_start);P(v,11,l.focus_num);P(v,12,l.click_pos||[]);P(v,6,l.copy);P(v,7,l.paste);P(v,8,l.enter);P(v,8,l.tab);P(v,13,l.left_shift);P(v,14,l.right_shift);P(v,15,l.left_cmd);P(v,16,l.right_cmd);P(v,17,l.left_shift_tab);P(v,18,l.right_shift_tab);P(v,19,l.ctrl_tab);P(v,20,l["delete"]);P(v,21,l.backspace);P(v,22,l.digits);P(v,23,l.num_pad);P(v,24,l.alpha);P(v,25,l.special);P(v,26,l.caps_lock);P(v,27,l.left_other);P(v,28,l.right_other);
P(v,29,l.arrow);P(v,30,l.auto_fill);P(v,32,l.hesitancy);D=[];var I=c(l,"flight",1);I&&D.push(I);(I=c(l,"dwell",2))&&D.push(I);(I=c(l,"pp_digraph",3))&&D.push(I);(I=c(l,"rr_digraph",4))&&D.push(I);(I=c(l,"pp_trigraph",5))&&D.push(I);(I=c(l,"rr_trigraph",6))&&D.push(I);eb(v,31,D);k.push(v)}0<k.length&&eb(p,66,k)}"undefined"===typeof dwn_ns.mouse_bm?C("No mouse_bm injected"):(l=dwn_ns.mouse_bm.getMouseRecord(),void 0===l?C("Didn't collect any mouse_bm"):(C("setMouseBM",l),k=new jb,P(k,4,l.left_click),
P(k,5,l.right_click),P(k,6,l.middle_click),P(k,7,l.scroll_click),P(k,3,l.num_strokes),P(k,1,l.mouse_off_screen),P(k,2,l.time_off_screen),f=[],(v=c(l,"dist",1))&&f.push(v),(v=c(l,"displacement",2))&&f.push(v),(v=c(l,"speed",3))&&f.push(v),(v=c(l,"time",4))&&f.push(v),(v=c(l,"curve",5))&&f.push(v),(l=c(l,"inflexion",6))&&f.push(l),eb(k,8,f),db(p,67,k)));"undefined"===typeof dwn_ns.touch_bm?C("No touch_bm injected"):(k=dwn_ns.touch_bm.getTouchRecord(),void 0===k?C("Didn't collect any touch_bm"):(C("setTouchBM",
k),f=new lb,P(f,1,k.swipe_strokes),P(f,4,k.swipe_stylus),P(f,2,k.swipe_left_handedness),P(f,3,k.swipe_right_handedness),l=[],(v=c(k,"radius",1))&&l.push(v),(v=c(k,"size",2))&&l.push(v),(v=c(k,"distance",3))&&l.push(v),(v=c(k,"displacement",4))&&l.push(v),(v=c(k,"speed",5))&&l.push(v),(v=c(k,"curve",6))&&l.push(v),(v=c(k,"inflexion",7))&&l.push(v),(v=c(k,"time",8))&&l.push(v),(v=c(k,"pressure",9))&&l.push(v),(v=c(k,"tiltx",10))&&l.push(v),(v=c(k,"tilty",11))&&l.push(v),eb(f,5,l),db(p,68,f)));"undefined"===
typeof dwn_ns.sensor_bm?C("No sensor_bm injected"):(k=dwn_ns.sensor_bm.getSensorRecord(),void 0===k?C("Didn't collect any sensor_bm"):(C("setSensorBM",k),f=new nb,l=k.orientation,"undefined"!==typeof l&&P(f,1,l),l=k.source,"undefined"!==typeof l&&P(f,2,l),l=[],(v=c(k,"ambient_light",1))&&l.push(v),(v=c(k,"orientation_pitch",2))&&l.push(v),(v=c(k,"orientation_yaw",3))&&l.push(v),(v=c(k,"orientation_roll",4))&&l.push(v),(v=c(k,"orientation_velocity_pitch",5))&&l.push(v),(v=c(k,"orientation_velocity_yaw",
6))&&l.push(v),(v=c(k,"orientation_velocity_roll",7))&&l.push(v),(v=c(k,"accelerometer_x",8))&&l.push(v),(v=c(k,"accelerometer_y",9))&&l.push(v),(v=c(k,"accelerometer_z",10))&&l.push(v),eb(f,3,l),db(p,69,f)));k=new Oa;f=O(p,1);null!=f&&N(k,1,f);f=O(p,2);null!=f&&J(k,2,f);f=O(p,3);null!=f&&J(k,3,f);f=O(p,4);null!=f&&N(k,4,f);f=O(p,5);null!=f&&null!=f&&Ra(k,5,f);f=O(p,6);null!=f&&N(k,6,f);f=O(p,7);null!=f&&J(k,7,f);f=O(p,8);null!=f&&J(k,8,f);f=O(p,9);null!=f&&N(k,9,f);f=O(p,10);null!=f&&N(k,10,f);f=
O(p,11);null!=f&&N(k,11,f);f=O(p,12);0<f.length&&Va(k,12,f);f=O(p,13);0<f.length&&Va(k,13,f);f=O(p,14);null!=f&&M(k,14,f);f=O(p,15);null!=f&&Ta(k,15,f);f=O(p,16);null!=f&&Ta(k,16,f);f=O(p,17);null!=f&&null!=f&&null!=f&&(H(k.a,136),H(k.a,f));f=O(p,18);null!=f&&Sa(k,18,f);f=O(p,19);null!=f&&Sa(k,19,f);f=O(p,20);null!=f&&J(k,20,f);f=O(p,21);null!=f&&M(k,21,f);f=O(p,22);null!=f&&M(k,22,f);f=O(p,23);null!=f&&J(k,23,f);f=O(p,24);null!=f&&M(k,24,f);f=O(p,25);null!=f&&J(k,25,f);f=O(p,26);null!=f&&M(k,26,
f);f=O(p,27);null!=f&&M(k,27,f);f=O(p,28);null!=f&&M(k,28,f);f=O(p,29);null!=f&&M(k,29,f);f=O(p,31);null!=f&&M(k,31,f);f=O(p,32);null!=f&&M(k,32,f);f=O(p,33);null!=f&&M(k,33,f);f=O(p,34);null!=f&&J(k,34,f);f=O(p,35);null!=f&&Ta(k,35,f);f=O(p,36);null!=f&&K(k,36,f);f=O(p,37);null!=f&&K(k,37,f);f=O(p,38);null!=f&&K(k,38,f);f=O(p,39);null!=f&&K(k,39,f);f=O(p,40);null!=f&&K(k,40,f);f=O(p,41);null!=f&&K(k,41,f);f=O(p,42);null!=f&&K(k,42,f);f=O(p,43);null!=f&&Ta(k,43,f);f=O(p,44);null!=f&&J(k,44,f);f=O(p,
45);null!=f&&J(k,45,f);f=O(p,46);null!=f&&J(k,46,f);f=O(p,47);null!=f&&J(k,47,f);f=O(p,48);null!=f&&M(k,48,f);f=O(p,49);null!=f&&N(k,49,f);f=O(p,50);null!=f&&Ta(k,50,f);f=O(p,51);null!=f&&J(k,51,f);f=O(p,52);null!=f&&Ta(k,52,f);f=O(p,53);null!=f&&N(k,53,f);f=O(p,54);null!=f&&N(k,54,f);f=O(p,55);if(0<f.length&&null!=f)for(l=0;l<f.length;l++)Sa(k,55,f[l]);f=O(p,56);null!=f&&M(k,56,f);f=O(p,57);null!=f&&null!=f&&Ra(k,57,f);f=O(p,58);null!=f&&null!=f&&Ra(k,58,f);f=O(p,59);null!=f&&null!=f&&Ra(k,59,f);
f=O(p,60);null!=f&&N(k,60,f);f=O(p,61);null!=f&&N(k,61,f);f=O(p,62);null!=f&&K(k,62,f);f=O(p,63);null!=f&&K(k,63,f);f=O(p,64);null!=f&&K(k,64,f);f=O(p,65);null!=f&&N(k,65,f);f=cb(p,gb,66);0<f.length&&Wa(k,66,f,sb);f=bb(p,jb,67);null!=f&&Ua(k,67,f,tb);f=bb(p,lb,68);null!=f&&Ua(k,68,f,ub);f=bb(p,nb,69);null!=f&&Ua(k,69,f,vb);p=new Uint8Array(k.b+k.a.length());l=k.c;v=l.length;for(D=f=0;D<v;D++)I=l[D],p.set(I,f),f+=I.length;l=Ma(k.a);p.set(l,f);k.c=[p];return hc(p)}function e(){var p=!0;"boolean"===
typeof dwn_ns.dwn_fp_ajax&&(p=dwn_ns.dwn_fp_ajax);C("dwn do_ajax",p);return p}function g(){var p=!0;"boolean"===typeof dwn_ns.dwn_fp_fetch&&(p=dwn_ns.dwn_fp_fetch);C("dwn do_fetch",p);return p}function h(){var p=this.a;p&&xa.then(function(k){k=d(k);p.setAttribute("value",k)},function(k){C("fp failed",k.toString())}).catch(function(k){C("Error for fp"+k.toString())})}function m(p,k){fetch(p,{method:"POST",body:k}).then(function(){C("Profiling fetch succeed",p)},function(f){C("Profiling fetch wrong",
p,f.toString())}).catch(function(f){C("Profiling fetch failed",p,f.toString())})}function q(p,k){var f=new XMLHttpRequest;f.open("POST",p,!0);f.onreadystatechange=function(){f.readyState==XMLHttpRequest.DONE&&200==f.status?C("Profiling ajax call succeed",p):C("Profiling ajax call failed",p,f.status)};f.send(k)}function n(p,k){return function(){var f=r("input");C("dwn profiling",k?"fetch":"ajax",p,f);k&&!g()||!k&&e();setTimeout(function(){k?g()?m(p,f):xa.then(function(l){l=d(l);f.append("dwn-profiling",
l);m(p,f)},function(l){C("Failed on fingerprint: "+l)}).catch(function(l){C("Failed on fingerprint: "+l)}):e()?q(p,f):xa.then(function(l){l=d(l);f.append("dwn-profiling",l);q(p,f)},function(l){C("Failed on fingerprint: "+l)}).catch(function(l){C("Failed on fingerprint: "+l)})},200)}}function r(p){p=document.getElementsByTagName(p);for(var k=new FormData,f=0;f<p.length;f++){var l=p[f],D=l.getAttribute("dwn_name");D&&(l=l.value,"string"===typeof D&&l&&(C("send dwn data",D,l),k.append(D,l)))}return k}
var w=null;"function"===typeof jd&&(w=jd(b));b=Lc();var x=Cc(),z=Hc(),E=dc(),L=Xc(),C=dwn_ns.dwn_log("main"),X=dwn_ns.add_event;C("Darwinium JS triggered!");var Fa=cd(),ea=yc(),ib;oc()&&(ib=Mc());var y=new pb;P(y,65,dd);P(y,57,Date.now());P(y,4,navigator.vendor||"");var A=Zc();P(y,1,A[0]);P(y,2,A[1]);P(y,3,A[2]);A=Vb(parseFloat(navigator.deviceMemory),void 0);"undefined"!==typeof A&&P(y,5,A);A=Yc();P(y,7,A[0]);P(y,8,A[1]);zb(y);A=navigator.oscpu;"undefined"!==typeof A&&P(y,6,A);A=navigator.a;"undefined"!==
typeof A&&P(y,10,A);wb(y);var Ga=Pc();A=Ga[0];Ga=Ga[1];"undefined"!==typeof A&&P(y,11,A);P(y,12,Ga||[]);A=ic();P(y,14,A.C);P(y,15,A.A);P(y,16,A.text);P(y,17,window.screen.colorDepth);Db(y);(A=Rc())&&2===A.length&&(P(y,51,A[0]),P(y,52,A[1]));A={ba:0,Y:1,$:2}[jc()];"undefined"!==typeof A&&P(y,18,A);A=kc();"undefined"!==typeof A&&P(y,19,A);Cb(y);A=$c();P(y,20,A.maxTouchPoints);P(y,21,A.O);P(y,22,A.P);A=Vb(parseInt(navigator.hardwareConcurrency),void 0);"undefined"!==typeof A&&P(y,23,A);A=Sc("reduce")?
!0:Sc("no-preference")?!1:void 0;"undefined"!==typeof A&&P(y,24,A);A=Qc();"undefined"!==typeof A&&P(y,25,A);A=Nc();"undefined"!==typeof A&&P(y,26,A);A=Nc();"undefined"!==typeof A&&P(y,27,A);a:{if(!Xb()&&!Yb())try{var U=!!window.indexedDB;break a}catch(p){U=!0;break a}U=void 0}"undefined"!==typeof U&&P(y,28,U);U=Oc("inverted")?!0:Oc("none")?!1:void 0;"undefined"!==typeof U&&P(y,29,U);Ab(y);Bb(y);P(y,33,!!window.openDatabase);(U=ad())&&2===U.length&&(P(y,53,U[0]),P(y,54,U[1]));ib&&ib.then(function(p){"undefined"!==
typeof p&&3<=p.length&&("undefined"!==typeof p[0]&&P(y,62,p[0]),"undefined"!==typeof p[1]&&P(y,63,p[1]),"undefined"!==typeof p[2]&&P(y,64,p[2]))},function(){}).catch(function(p){C("Failed location promise: "+p)});var xa=Promise.all([b,x,z,E,L,Fa,ea]).then(function(p){var k=p[0],f=p[1],l=p[2],D=p[3],v=t(p[4]),I=v.next().value,oa=v.next().value,Jb=v.next().value;v=v.next().value;k&&2===k.length&&(P(y,34,k[0]),P(y,35,k[1]));k=p[5];"undefined"!==typeof k&&(1<=k.length&&P(y,56,k[0]),2<=k.length&&P(y,49,
k[1]));p=p[6];"undefined"!==typeof p&&3<=p.length&&(P(y,59,p[0]),P(y,60,p[1]),P(y,61,p[2]));null!==f&&"undefined"!==typeof f&&P(y,55,f||[]);P(y,43,D);null!==I&&P(y,44,I);null!==oa&&P(y,45,oa);null!==Jb&&P(y,46,Jb);null!==v&&P(y,47,v);null!==l&&"undefined"!==typeof l&&(P(y,36,l.default),P(y,37,l.F),P(y,38,l.M),P(y,39,l.L),P(y,40,l.H),P(y,41,l.min),P(y,42,l.N));P(y,58,Date.now());return y}).catch(function(p){C("Failed fp_stuff: ",p)});(function(){for(var p=document.getElementsByTagName("form"),k=0;k<
p.length;k++){var f=p[k],l=f.action,D;if(D=l)a:{try{D=(new URL(l)).hostname;break a}catch(v){}D=null}D&&(l=document.createElement("input"),l.type="hidden",l.name="dwn-profiling",l.className="dwn_field",X(f,"submit",h),f.a=l,f.appendChild(l))}})();(function(p){for(var k=document.getElementsByTagName(p),f=0;f<k.length;f++){var l=k[f],D=l.getAttribute("dwn_submit");if(D&&(C(p,"found dwn_submit",l.name,l.id,D),l)){var v=D.split(",");if(0<v.length){var I=v[0].trim().toLowerCase();D="click";1<v.length&&
(D=v[1].trim().toLowerCase());var oa="fetch";2<v.length&&(oa=v[2].trim().toLowerCase());C("setDwnSubmitEvent",I,D,oa);v=n(I,"fetch"==oa);X(l,D,v)}else C("set_dwn_submit failed, no profiling url")}}})("input");(function(){if(e()){if("undefined"!==typeof window.XMLHttpRequest.prototype.open){var p=window.XMLHttpRequest.prototype.open;window.XMLHttpRequest.prototype.open=function(f,l){this.a=l;return p.apply(this,arguments)}}if("undefined"!==typeof window.XMLHttpRequest.prototype.send){var k=window.XMLHttpRequest.prototype.send;
window.XMLHttpRequest.prototype.send=function(f){var l=arguments,D=this;C("AJAX url: ",this.a);return"undefined"!==typeof this.a&&pc(this.a)?xa.then(function(v){v=d(v);D.setRequestHeader.apply(D,["Dwn-Profiling",v]);k.apply(D,l)},function(){k.apply(D,l)}):k.apply(this,arguments)}}}})();(function(){if(g()){var p=window.fetch;window.fetch=function(k,f){return typeof k===typeof Request||(k=new Request(k),C("fetch url: ",k.url),"undefined"!==typeof k.url&&pc(k.url))?xa.then(function(l){l=d(l);k.headers.set("Dwn-Profiling",
l);return p(k,f)},function(){return p(k,f)}).catch(function(l){C("Failed fetch: "+l)}):p(k,f)}}})();return w};
{%- if key_bm is not defined or key_bm %} /* raw_field_bm.js */
dwn_ns=dwn_ns||{};dwn_ns.dwn_log||(dwn_ns.dwn_log=function(b){"string"!==typeof b&&(b="common");var c="enable_log";c=c+"_"+b;return function(){var f=arguments,e=!1;try{e={{ profiling.javascript.debug_enable }},"boolean"===typeof e&&e||"boolean"===typeof dwn_ns[c]&&(e=dwn_ns[c])}catch(w){}if(e){e="";for(var m=0;m<f.length;m++){var h=f[m];"object"===typeof h?h=h?JSON.stringify(h,null,4):"null":"undefined"===typeof h&&(h="undefined");0===m?e=h:e+=", "+h}f=(new Date).toISOString()+"["+b+"]: "+e;console.log(f)}}});
dwn_ns.add_event||(dwn_ns.add_event=function(b,c,f){try{if("addEventListener"in window)b.addEventListener(c,f,!1);else{var e="on"+c;if("attachEvent"in window)b.attachEvent(e,f);else{var m=b[e];b[e]="undefined"===typeof m?f:function(){m();f(event)}}}}catch(h){console.error("Failed to add DwnEvent:",b,c,h)}});
dwn_ns.remove_event||(dwn_ns.remove_event=function(b,c,f){try{"removeEventListener"in window?b.removeEventListener(c,f,!1):"dettachEvent"in window?b.detachEvent("on"+c,f):console.error("Can't remove event:",b,c)}catch(e){console.error("Failed to add DwnEvent:",b,c,e)}});
dwn_ns.calc_stats||(dwn_ns.calc_stats=function(b,c,f){if("undefined"!==typeof c&&0!==c.length){var e=function(k){return Math.round(100*k)/100},m=c.length,h=Math.floor(m/2);c.sort(function(k,n){return k-n});var w=c.reduce(function(k,n){return k+n},0),z=c[0],A=c[m-1],x=Math.floor(w/m);m=Math.sqrt(c.map(function(k){return Math.pow(k-x,2)}).reduce(function(k,n){return k+n},0)/m);var p=0!==h%2?c[h]:Math.floor((c[h-1]+c[h])/2);c=c.map(function(k){return Math.abs(k-p)}).sort(function(k,n){return k-n});h=
0!==h%2?c[h]:Math.floor((c[h-1]+c[h])/2);b[f+"_avg"]=e(x);b[f+"_std_dev"]=e(m);b[f+"_min"]=e(z);b[f+"_max"]=e(A);b[f+"_mad"]=e(h);b[f+"_median"]=e(p)}});dwn_ns.add_value||(dwn_ns.add_value=function(b,c,f,e){"undefined"!==typeof f&&(b[c]="boolean"===typeof e&&e||"undefined"===typeof b[c]?f:b[c]+f)});dwn_ns.add_count||(dwn_ns.add_count=function(b,c){"undefined"===typeof b[c]?b[c]=1:b[c]++});dwn_ns.time_diff||(dwn_ns.time_diff=function(b){return Date.now()-b});dwn_ns=dwn_ns||{};dwn_ns.field_focus=function(b,c){"undefined"===typeof dwn_ns.field_bm&&(dwn_ns.field_bm={});"undefined"===typeof dwn_ns.field_bm[c]&&(dwn_ns.field_bm[c]=new dwn_ns.field_focus_bm(b,c))};dwn_ns=dwn_ns||{};
dwn_ns.field_focus_bm=function(b,c){function f(d){d=d||window.event;var l=d.which||d.keyCode,q=d.key,y=d.location;switch(l){case 17:B=!0;break;case 91:g(a,"left_cmd");break;case 93:g(a,"right_cmd");break;case 13:g(a,"enter");break;case 9:C?g(a,"left_shift_tab"):D?g(a,"right_shift_tab"):B?g(a,"ctrl_tab"):g(a,"tab");break;case 46:g(a,"delete");break;case 8:g(a,"backspace");break;case 37:case 39:case 38:case 40:g(a,"arrow");break;case 20:g(a,"caps_lock");break;case 16:1===d.location?(g(a,"left_shift"),
C=!0):2===d.location&&(g(a,"right_shift"),D=!0);break;default:65<=l&&90>=l?g(a,"alpha"):96<=l&&105>=l?g(a,"num_pad"):q&&("0"<=q&&"9">=q?3===y?g(a,"num_pad"):g(a,"digits"):1===q.length&&g(a,"special"))}switch(d.location){case 0:0===a.focus_start&&(a.focus_start=t(0),g(a,"focus_num"));d=t(a.focus_start);E[l]=d;break;case 1:16!==l&&93!==l&&g(a,"left_other");break;case 2:16!==l&&91!==l&&g(a,"right_other")}"undefined"===typeof l?a.c=t(0):a.c=void 0}function e(d){d=d||window.event;var l=d.which||d.keyCode;
switch(l){case 17:B=!1;break;case 16:1===d.location?C=!1:2===d.location&&(D=!1)}if(d=E[l]){var q=t(a.focus_start);u.push({b:d,a:q});E[l]=void 0}}function m(){if("undefined"!==typeof a.c){var d=t(a.c);5>d&&(p("AUTO-FILL detectted",d),g(a,"auto_fill"))}}function h(){g(a,"focus_num");0===a.focus_start&&(a.focus_start=t(0))}function w(){var d=u.length;0<d&&(d=u[d-1],d=t(a.focus_start)-d.a,K(a,"hesitancy",d),p("hesitancy time",d))}function z(){g(a,"copy")}function A(){g(a,"paste")}function x(){a.click_pos.push(this.selectionStart.toString())}
var p=dwn_ns.dwn_log("key_bm"),k=dwn_ns.calc_stats,n=dwn_ns.add_event,g=dwn_ns.add_count,K=dwn_ns.add_value,t=dwn_ns.time_diff,a={},u=[],E={},C=!1,D=!1,B=!1;this.getKeyRecords=function(){p("key_record",u);var d=u.length;if(1<d){var l=[],q=[],y=[],H=[],I=[],J=[],v=u[0];l.push(v.a-v.b);for(var F=1;F<d;F++){var r=u[F];l.push(r.a-r.b);q.push(r.b-v.a);y.push(r.b-v.b);H.push(r.a-v.a);G&&(I.push(r.b-G.b),J.push(r.a-G.a));var G=v;v=r}k(a,l,"dwell");k(a,q,"flight");k(a,y,"pp_digraph");k(a,H,"rr_digraph");
k(a,I,"pp_trigraph");k(a,J,"rr_trigraph")}return a};"undefined"===typeof b?p("Didn't pass element in"):"undefined"===typeof c?p("Didn't pass context in"):(p("init field","context: "+c,"type: "+b.type,"id: "+b.id),a.type=b.type,a.name=b.name,a.id=b.id,a.context=c,a.value_length=0,a.focus_start=0,a.click_pos=[],n(b,"keyup",e),n(b,"keydown",f),n(b,"focus",h),n(b,"click",x),n(b,"change",m),n(b,"focusout",w),n(b,"copy",z),n(b,"paste",A))};
{% endif %}
{%- if mouse_bm is not defined or mouse_bm %} /* raw_mouse_bm.js */
dwn_ns=dwn_ns||{};dwn_ns.dwn_log||(dwn_ns.dwn_log=function(b){"string"!==typeof b&&(b="common");var a="enable_log";a=a+"_"+b;return function(){var e=arguments,c=!1;try{c={{ profiling.javascript.debug_enable }},"boolean"===typeof c&&c||"boolean"===typeof dwn_ns[a]&&(c=dwn_ns[a])}catch(x){}if(c){c="";for(var k=0;k<e.length;k++){var f=e[k];"object"===typeof f?f=f?JSON.stringify(f,null,4):"null":"undefined"===typeof f&&(f="undefined");0===k?c=f:c+=", "+f}e=(new Date).toISOString()+"["+b+"]: "+c;console.log(e)}}});
dwn_ns.add_event||(dwn_ns.add_event=function(b,a,e){try{if("addEventListener"in window)b.addEventListener(a,e,!1);else{var c="on"+a;if("attachEvent"in window)b.attachEvent(c,e);else{var k=b[c];b[c]="undefined"===typeof k?e:function(){k();e(event)}}}}catch(f){console.error("Failed to add DwnEvent:",b,a,f)}});
dwn_ns.remove_event||(dwn_ns.remove_event=function(b,a,e){try{"removeEventListener"in window?b.removeEventListener(a,e,!1):"dettachEvent"in window?b.detachEvent("on"+a,e):console.error("Can't remove event:",b,a)}catch(c){console.error("Failed to add DwnEvent:",b,a,c)}});
dwn_ns.calc_stats||(dwn_ns.calc_stats=function(b,a,e){if("undefined"!==typeof a&&0!==a.length){var c=function(h){return Math.round(100*h)/100},k=a.length,f=Math.floor(k/2);a.sort(function(h,m){return h-m});var x=a.reduce(function(h,m){return h+m},0),g=a[0],A=a[k-1],n=Math.floor(x/k);k=Math.sqrt(a.map(function(h){return Math.pow(h-n,2)}).reduce(function(h,m){return h+m},0)/k);var w=0!==f%2?a[f]:Math.floor((a[f-1]+a[f])/2);a=a.map(function(h){return Math.abs(h-w)}).sort(function(h,m){return h-m});f=
0!==f%2?a[f]:Math.floor((a[f-1]+a[f])/2);b[e+"_avg"]=c(n);b[e+"_std_dev"]=c(k);b[e+"_min"]=c(g);b[e+"_max"]=c(A);b[e+"_mad"]=c(f);b[e+"_median"]=c(w)}});dwn_ns.add_value||(dwn_ns.add_value=function(b,a,e,c){"undefined"!==typeof e&&(b[a]="boolean"===typeof c&&c||"undefined"===typeof b[a]?e:b[a]+e)});dwn_ns.add_count||(dwn_ns.add_count=function(b,a){"undefined"===typeof b[a]?b[a]=1:b[a]++});dwn_ns.time_diff||(dwn_ns.time_diff=function(b){return Date.now()-b});dwn_ns=dwn_ns||{};dwn_ns.add_event(window,"load",function(){"undefined"===typeof dwn_ns.mouse_bm&&(dwn_ns.mouse_bm=new dwn_ns.mouse_bm_load(100))});dwn_ns=dwn_ns||{};
dwn_ns.mouse_bm_load=function(b){var a=dwn_ns.dwn_log("mouse_bm"),e=dwn_ns.add_event,c=dwn_ns.calc_stats,k=dwn_ns.add_value,f=dwn_ns.add_count,x=dwn_ns.time_diff,g={},A=b?b:100,n=[],w=[],h=[],m=0;this.getMouseRecord=function(){var d=h.length;if(0===d)return g;var t=[],q=[],p=[],u=[],z=[],r=[];g.num_strokes=d;for(var y=1;y<d;y++){var l=h[y];t.push(l.b);q.push(l.a);p.push(l.c);0!==l.c&&u.push(l.b/l.c);if(0!==l.a){var v=l.b/l.a;z.push((v-1)/(v+1))}r.push(l.f)}c(g,t,"dist");c(g,q,"displacement");c(g,
p,"time");c(g,u,"speed");c(g,z,"curve");c(g,r,"inflexion");return g};a("init mouse movement");g.start_time=x(0);e(window,"click",function(d){d=d||window.event;switch(d.button){case 0:f(g,"left_click");break;case 1:f(g,"middle_click");break;case 2:f(g,"right_click")}});e(window,"mousemove",function(d){d=d||window.event;var t=x(g.start_time),q=n.length;d={time:t,x:d.clientX,y:d.clientY};if(0===q)n.push(d);else if(t-n[q-1].time>A){if(3<n.length){q=t=0;for(var p=d=n[0],u=d,z=d.time,r,y,l=1;l<n.length;l++){u=
n[l];var v=p.x-u.x;p=p.y-u.y;t+=Math.sqrt(Math.pow(v,2)+Math.pow(p,2));v=0===v?0:0<v?1:-1;p=0===p?0:0<p?1:-1;r&&y&&(0>v*r||0>p*y)&&q++;r=v;y=p;p=u}r={g:z,c:u.time-z,a:Math.sqrt(Math.pow(u.x-d.x,2)+Math.pow(u.y-d.y,2)),b:t,f:q};a("Got a stroke",JSON.stringify(r));h.push(r)}n=[]}else r=n[q-1],r.x===d.x&&r.y===d.y||n.push(d);0!==m&&(f(g,"mouse_off_screen"),k(g,"time_off_screen",x(m)),m=0,a("Mouse came back in screen",g.mouse_off_screen,g.time_off_screen))});e(window,"mouseout",function(d){d=d||window.event;
(d=d.relatedTarget||d.toElement)&&"HTML"!==d.nodeName||0===m&&(m=Date.now())});e(window,"mousewheel",function(){var d=x(g.start_time),t=w.length,q={time:d};0===t?w.push(q):d-w[t-1].time>A?(f(g,"scroll_click"),w=[]):w.push(q)})};
{% endif %}
{%- if touch_bm is not defined or touch_bm %} /* raw_touch_bm.js */
dwn_ns=dwn_ns||{};dwn_ns.dwn_log||(dwn_ns.dwn_log=function(c){"string"!==typeof c&&(c="common");var b="enable_log";b=b+"_"+c;return function(){var f=arguments,d=!1;try{d={{ profiling.javascript.debug_enable }},"boolean"===typeof d&&d||"boolean"===typeof dwn_ns[b]&&(d=dwn_ns[b])}catch(k){}if(d){d="";for(var m=0;m<f.length;m++){var h=f[m];"object"===typeof h?h=h?JSON.stringify(h,null,4):"null":"undefined"===typeof h&&(h="undefined");0===m?d=h:d+=", "+h}f=(new Date).toISOString()+"["+c+"]: "+d;console.log(f)}}});
dwn_ns.add_event||(dwn_ns.add_event=function(c,b,f){try{if("addEventListener"in window)c.addEventListener(b,f,!1);else{var d="on"+b;if("attachEvent"in window)c.attachEvent(d,f);else{var m=c[d];c[d]="undefined"===typeof m?f:function(){m();f(event)}}}}catch(h){console.error("Failed to add DwnEvent:",c,b,h)}});
dwn_ns.remove_event||(dwn_ns.remove_event=function(c,b,f){try{"removeEventListener"in window?c.removeEventListener(b,f,!1):"dettachEvent"in window?c.detachEvent("on"+b,f):console.error("Can't remove event:",c,b)}catch(d){console.error("Failed to add DwnEvent:",c,b,d)}});
dwn_ns.calc_stats||(dwn_ns.calc_stats=function(c,b,f){if("undefined"!==typeof b&&0!==b.length){var d=function(e){return Math.round(100*e)/100},m=b.length,h=Math.floor(m/2);b.sort(function(e,g){return e-g});var k=b.reduce(function(e,g){return e+g},0),r=b[0],x=b[m-1],w=Math.floor(k/m);m=Math.sqrt(b.map(function(e){return Math.pow(e-w,2)}).reduce(function(e,g){return e+g},0)/m);var a=0!==h%2?b[h]:Math.floor((b[h-1]+b[h])/2);b=b.map(function(e){return Math.abs(e-a)}).sort(function(e,g){return e-g});h=
0!==h%2?b[h]:Math.floor((b[h-1]+b[h])/2);c[f+"_avg"]=d(w);c[f+"_std_dev"]=d(m);c[f+"_min"]=d(r);c[f+"_max"]=d(x);c[f+"_mad"]=d(h);c[f+"_median"]=d(a)}});dwn_ns.add_value||(dwn_ns.add_value=function(c,b,f,d){"undefined"!==typeof f&&(c[b]="boolean"===typeof d&&d||"undefined"===typeof c[b]?f:c[b]+f)});dwn_ns.add_count||(dwn_ns.add_count=function(c,b){"undefined"===typeof c[b]?c[b]=1:c[b]++});dwn_ns.time_diff||(dwn_ns.time_diff=function(c){return Date.now()-c});dwn_ns=dwn_ns||{};dwn_ns.add_event(window,"load",function(){"undefined"===typeof dwn_ns.touch_bm&&(dwn_ns.touch_bm=new dwn_ns.touch_bm_load(100))});dwn_ns=dwn_ns||{};
dwn_ns.touch_bm_load=function(){function c(){return h(k.start_time)}var b=dwn_ns.dwn_log("touch_bm"),f=dwn_ns.add_event,d=dwn_ns.calc_stats,m=dwn_ns.add_count,h=dwn_ns.time_diff,k={},r=[],x=[],w=[];this.getTouchRecord=function(){var a=x.length;if(0!==a){for(var e=[],g=[],n=[],u=[],t=[],A=[],q=[],p=[],y=0;y<a;y++){var l=x[y];e.push(l.b);g.push(l.a);n.push(l.c);A.push(l.f);p.push(l.g);l.c&&u.push(l.b/l.c);l.size&&q.push(l.size);0!==l.a&&(l=l.b/l.a,t.push((l-1)/(l+1)))}d(k,e,"dist");d(k,g,"displacement");
d(k,n,"time");d(k,u,"speed");d(k,t,"curve");d(k,A,"inflexion");d(k,q,"size");d(k,p,"radius");a=w.length;if(0!==a){e=[];g=[];n=[];for(u=0;u<a;u++)t=w[u],e.push(t.pressure),g.push(t.tiltX),n.push(t.tiltY);d(k,e,"pressure");d(k,g,"tiltx");d(k,n,"tilty")}return k}};b("init touch movement");k.start_time=h(0);f(window,"touchstart",function(a){a=a||window.event;r=[];var e=c(),g=a.pageX||a.layerX||a.clientX,n=a.pageY||a.layerY||a.clientY,u;if(a.touches&&0<a.touches.length){var t=a.touches[0].radiusX;a=a.touches[0].radiusY;
t&&a&&(u=(t+a)/2)}r.push({time:e,x:g,y:n,size:u})});f(window,"touchmove",function(a){a=a||window.event;r=r||[];var e=c();r.push({time:e,x:a.pageX||a.layerX||a.clientX,y:a.pageY||a.layerY||a.clientY})});f(window,"touchend",function(a){a=a||window.event;r=r||[];var e=c();r.push({time:e,x:a.pageX||a.layerX||a.clientX,y:a.pageY||a.layerY||a.clientY});if(3<r.length){a=r;b("get swipe info",a.length);e=a.length;if(!(1>=e)){var g=a[0],n=a[e-1],u=g.size,t=g.time,A=n.time-t,q=n.x-g.x,p=n.y-g.y,y=Math.sqrt(Math.pow(q,
2)+Math.pow(p,2)),l=0;0!==q&&0!==p&&(0<q&&0>p||0>q&&0<p?m(k,"left_handedness"):m(k,"right_handedness"));if(2<e){var z=window.innerWidth;q=window.innerHeight;p=a[Math.round(e/2)];z=(Math.sqrt(Math.pow(z-g.x,2)+Math.pow(q-g.y,2))+Math.sqrt(Math.pow(z-p.x,2)+Math.pow(q-p.y,2))+Math.sqrt(Math.pow(z-n.x,2)+Math.pow(q-n.y,2)))/3}var v=g;g=0;for(n=1;n<e;n++){q=a[n];p=v.x-q.x;v=v.y-q.y;l+=Math.sqrt(Math.pow(p,2)+Math.pow(v,2));p=0===p?0:0<p?1:-1;v=0===v?0:0<v?1:-1;B&&C&&(0>p*B||0>v*C)&&g++;var B=p;var C=
v;v=q}x.push({h:t,c:A,g:z,size:u,b:l,a:y,f:g})}m(k,"swipe_strokes")}});f(window,"pointerdown",function(a){a=a||window.event;b("pointer down",a.pointerType);if("pen"!==a.pointerType){var e=c();w.push({time:e,pressure:a.pressure,tiltX:a.tiltX,tiltY:a.tiltY})}})};
{% endif %}
{%- if sensor_bm is not defined or sensor_bm %} /* raw_sensor_bm.js */
dwn_ns=dwn_ns||{};dwn_ns.dwn_log||(dwn_ns.dwn_log=function(c){"string"!==typeof c&&(c="common");var b="enable_log";b=b+"_"+c;return function(){var g=arguments,f=!1;try{f={{ profiling.javascript.debug_enable }},"boolean"===typeof f&&f||"boolean"===typeof dwn_ns[b]&&(f=dwn_ns[b])}catch(x){}if(f){f="";for(var m=0;m<g.length;m++){var h=g[m];"object"===typeof h?h=h?JSON.stringify(h,null,4):"null":"undefined"===typeof h&&(h="undefined");0===m?f=h:f+=", "+h}g=(new Date).toISOString()+"["+c+"]: "+f;console.log(g)}}});
dwn_ns.add_event||(dwn_ns.add_event=function(c,b,g){try{if("addEventListener"in window)c.addEventListener(b,g,!1);else{var f="on"+b;if("attachEvent"in window)c.attachEvent(f,g);else{var m=c[f];c[f]="undefined"===typeof m?g:function(){m();g(event)}}}}catch(h){console.error("Failed to add DwnEvent:",c,b,h)}});
dwn_ns.remove_event||(dwn_ns.remove_event=function(c,b,g){try{"removeEventListener"in window?c.removeEventListener(b,g,!1):"dettachEvent"in window?c.detachEvent("on"+b,g):console.error("Can't remove event:",c,b)}catch(f){console.error("Failed to add DwnEvent:",c,b,f)}});
dwn_ns.calc_stats||(dwn_ns.calc_stats=function(c,b,g){if("undefined"!==typeof b&&0!==b.length){var f=function(n){return Math.round(100*n)/100},m=b.length,h=Math.floor(m/2);b.sort(function(n,l){return n-l});var x=b.reduce(function(n,l){return n+l},0),y=b[0],z=b[m-1],d=Math.floor(x/m);m=Math.sqrt(b.map(function(n){return Math.pow(n-d,2)}).reduce(function(n,l){return n+l},0)/m);var v=0!==h%2?b[h]:Math.floor((b[h-1]+b[h])/2);b=b.map(function(n){return Math.abs(n-v)}).sort(function(n,l){return n-l});h=
0!==h%2?b[h]:Math.floor((b[h-1]+b[h])/2);c[g+"_avg"]=f(d);c[g+"_std_dev"]=f(m);c[g+"_min"]=f(y);c[g+"_max"]=f(z);c[g+"_mad"]=f(h);c[g+"_median"]=f(v)}});dwn_ns.add_value||(dwn_ns.add_value=function(c,b,g,f){"undefined"!==typeof g&&(c[b]="boolean"===typeof f&&f||"undefined"===typeof c[b]?g:c[b]+g)});dwn_ns.add_count||(dwn_ns.add_count=function(c,b){"undefined"===typeof c[b]?c[b]=1:c[b]++});dwn_ns.time_diff||(dwn_ns.time_diff=function(c){return Date.now()-c});dwn_ns=dwn_ns||{};dwn_ns=dwn_ns||{};
dwn_ns.sensor_bm=new function(){function c(a,p){try{navigator.permissions.query({name:a}).then(function(k){"granted"===k.state?(d("Permission granted for "+a),p()):d("Permission denied for "+a,k.state)}).catch(function(k){d("Permission error for "+a,k)})}catch(k){d("Failed to request permission for "+a,k.toString())}}function b(){if((E||G)&&u)d("Device motion permission checked before");else try{DeviceMotionEvent.requestPermission().then(function(a){"granted"===a?(d("Device motion permission granted"),E=
!0,v(window,"devicemotion",y),v(window,"deviceorientation",z),w=A.c,u=!0):(d("Device motion permission denied "+a),G=!0)}).catch(function(a){d("Device motion permission error",a)})}catch(a){d("Failed to request device motion permission",a)}}function g(){try{e.gyroscope=new Gyroscope({frequency:1}),e.gyroscope.addEventListener("reading",function(){B.push({x:e.gyroscope.x,y:e.gyroscope.y,z:e.gyroscope.z})}),e.gyroscope.start()}catch(a){d("Gyroscope failed",a.toString())}}function f(){try{e.ambientlight=
new AmbientLightSensor({frequency:1}),e.ambientlight.addEventListener("reading",function(){H.push(e.ambientlight.g)}),e.ambientlight.start()}catch(a){d("AmbientLightSensor failed",a.toString())}}function m(){try{e.accelerometer=new Accelerometer({frequency:1}),e.accelerometer.addEventListener("reading",function(){C.push({x:e.accelerometer.x,y:e.accelerometer.y,z:e.accelerometer.z})}),e.accelerometer.start()}catch(a){d("Accelerometer failed",a.toString())}}function h(){}function x(){try{if(0==Object.keys(q).length){d("No Sensors API started");
return}w=A.f;e.absolute_orientation=new AbsoluteOrientationSensor({frequency:1,h:"device"});e.absolute_orientation.addEventListener("reading",function(){try{var a=e.absolute_orientation.a[0],p=e.absolute_orientation.a[1],k=e.absolute_orientation.a[2],r=e.absolute_orientation.a[3];D.push({x:Math.atan2(2*(a*p+k*r),1-2*(Math.pow(p,2)+Math.pow(k,2))),y:Math.asin(2*(a*r+p*k)),z:Math.atan2(2*(a*r+p*k),1-2*(Math.pow(k,2)+Math.pow(r,2)))})}catch(t){d("AbsoluteOrientationSensor reading failed",t.toString())}});
e.absolute_orientation.start()}catch(a){d("AbsoluteOrientatinoSensor failed",a.toString())}d("Sensors API started",Object.keys(q))}function y(a){C.push({x:a.acceleration.x,y:a.acceleration.y,z:a.acceleration.z});B.push({x:a.rotationRate.gamma,y:a.rotationRate.beta,z:a.rotationRate.alpha})}function z(a){D.push({x:a.gamma,y:a.beta,z:a.alpha})}var d=dwn_ns.dwn_log("sensor_bm"),v=dwn_ns.add_event,n=dwn_ns.remove_event,l=dwn_ns.calc_stats,F=dwn_ns.add_value,A={b:0,c:1,f:2},w=A.b,q={},e={},E=!1,G=!1,u=
!1,D=[],B=[],H=[],C=[];this.askMotionPermission=function(){b()};this.sensors_start=function(){if(u)d("sensors already started",e);else{for(var a in e)d("sensor "+a+"starting"),e[a].start(),d("sensor "+a+"started"),u=!0;b();d("sensors started")}};this.sensors_stop=function(){if(u){for(var a in e)e[a].stop();E&&(n(window,"devicemotion",y),n(window,"deviceorientation",z));u=!1;d("sensors stopped")}else d("sensors already stopped",e)};this.getSensorRecord=function(){d("Sensor source",w);if(w!=A.b){F(q,
"source",w,!0);d("window size",window.innerWidth,window.innerHeight);window.innerWidth<window.innerHeight?F(q,"orientation",1,!0):F(q,"orientation",2,!0);for(var a=[],p=[],k=[],r=0;r<D.length;r++){var t=D[r];a.push(t.x);p.push(t.y);k.push(t.z)}l(q,a,"orientation_roll");l(q,p,"orientation_pitch");l(q,k,"orientation_yaw");a=[];p=[];k=[];for(r=0;r<B.length;r++)t=B[r],a.push(t.x),p.push(t.y),k.push(t.z);l(q,a,"orientation_velocity_roll");l(q,p,"orientation_velocity_pitch");l(q,k,"orientation_velocity_yaw");
a=[];p=[];k=[];for(r=0;r<C.length;r++)t=C[r],a.push(t.x),p.push(t.y),k.push(t.z);l(q,a,"accelerometer_x");l(q,p,"accelerometer_y");l(q,k,"accelerometer_z");l(q,H,"ambient_light");return q}};this.isSensorStarted=function(){return u};try{c("gyroscope",g),c("accelerometer",m),c("ambient-light-sensor",f),c("magnetometer",h),setTimeout(x,300)}catch(a){d("Failed to init_sensor_api",a)}(function(){var a=!1;try{"boolean"===typeof Dwn_device_sensor_enabled?a=Dwn_device_sensor_enabled:"boolean"===typeof dwn_ns.device_sensor_enabled&&
(a=dwn_ns.device_sensor_enabled)}catch(p){a=!1}d("isDeviceSensorEnabled",a);return a})()&&(d("init_device_motion_event"),"undefined"===typeof DeviceMotionEvent||"function"!==typeof DeviceMotionEvent.requestPermission?d("device motion event NOT supported"):(d("add window.click event for DeviceMotionEvent"),v(window,"click",b)))};
{% endif %}
</script>
